// packages/vue/src/components/DateSelector.vue
<script setup lang="ts">
import type { Ref } from 'vue'
import { ref, computed, onBeforeUnmount, watch, watchEffect } from 'vue'
import { daysInMonth, splitDate } from '@geckou/ui-core'
import { FormValidationManager } from '@/scripts/form-validation-manager'
import InputBox from '@/components/InputBox.vue'
import KeyboardArrowDownIcon from '@/components/Icon/KeyboardArrowDownIcon.vue'
import TextButton from '@/components/TextButton.vue'

const emit = defineEmits<{ (e: 'update:modelValue', newValue: string): void }>()

type Date = {
  year: string
  month: string
  day?: string
}
const props = withDefaults(
  defineProps<{
    name: string
    modelValue: string
    isRequired?: boolean
    formValidationManager?: FormValidationManager | null
    type?: 'date' | 'month'
  }>(),
  {
    formValidationManager: null,
    type: 'date',
  }
)

const birthday: Ref<Date> = ref({
  year: '',
  month: '',
  day: '',
})

const yearsOptions = computed(() => {
  const today = new Date()
  const maxYear = today.getFullYear() - 100
  const currentYear = today.getFullYear() - 14
  const years = Array.from({ length: currentYear - maxYear + 1 }, (_, i) =>
    (maxYear + i).toString()
  )
  return years.map((year) => ({ label: year, value: year }))
})

const monthOptions = computed(() => {
  return Array.from({ length: 12 }, (_, i) => {
    const month = (i + 1).toString()
    return {
      label: month,
      value: month.padStart(2, '0'),
    }
  })
})

const daysInSelectedMonth = computed(() => {
  const month = Number(birthday.value?.month)
  if (!month) {
    return 31
  }

  // 年が未選択のときは閏年を含む最大日数になるよう 2000 年を使う
  const year = Number(birthday.value?.year) || 2000
  return daysInMonth(year, month)
})

const dayOptions = computed(() => {
  const days = []
  const daysInMouth = daysInSelectedMonth.value

  for (let day = 1; day <= daysInMouth; day++) {
    const dayString = day.toString()
    days.push(dayString)
  }

  return days.map((day) => ({
    label: day,
    value: String(day).padStart(2, '0'),
  }))
})

const openDropdown = (e: MouseEvent) => {
  const target = e.currentTarget as HTMLElement
  const select = target.firstElementChild as HTMLSelectElement
  if (select) {
    select.click()
  }
}

const selectItem = (event: Event, key: 'year' | 'day' | 'month') => {
  const target = event.target as HTMLSelectElement
  const { value } = target
  birthday.value = { ...birthday.value, [key]: value }
}

// 月や年を変えて日が存在しなくなった場合は、その月の末日に丸める
watch(daysInSelectedMonth, (days) => {
  const day = Number(birthday.value.day)
  if (day && day > days) {
    birthday.value = { ...birthday.value, day: String(days).padStart(2, '0') }
  }
})

const EMPTY_BIRTHDAY = { year: '', month: '', day: '' }

// value が空に戻されたときもリセットする（以前は前の選択が残っていた）
watchEffect(() => {
  birthday.value = props.modelValue
    ? splitDate(props.modelValue)
    : { ...EMPTY_BIRTHDAY }
})

const setValid = (isValid: boolean): void => {
  if (props.formValidationManager) {
    props.formValidationManager.setValid(props.name, isValid)
  }
}

setValid(!props.isRequired)

watch(
  () => birthday.value,
  (newValue) => {
    const isFilled = Boolean(
      newValue.year &&
      newValue.month &&
      (props.type === 'month' || newValue.day)
    )
    const isEmpty = !newValue.year && !newValue.month && !newValue.day

    setValid(props.isRequired ? isFilled : isFilled || isEmpty)

    if (isEmpty) {
      emit('update:modelValue', '')
    } else if (!isFilled) {
      return
    } else {
      const parts =
        props.type === 'month'
          ? [newValue.year, newValue.month]
          : [newValue.year, newValue.month, newValue.day]
      emit('update:modelValue', parts.filter(Boolean).join('-'))
    }
  },
  { deep: true }
)

// アンマウント後も無効判定が残らないように登録を解除する
onBeforeUnmount(() => props.formValidationManager?.remove(props.name))
</script>

<template>
  <InputBox :class="$style.date_selector">
    <div :class="[$style.selector_wrapper]" @click="openDropdown($event)">
      <select
        :value="birthday.year"
        :class="$style.year"
        @change="selectItem($event, 'year')"
      >
        <option disabled selected value="">年</option>
        <option
          v-for="year in yearsOptions"
          :key="year.value"
          :value="year.value"
        >
          {{ year.label }}
        </option>
      </select>
      <KeyboardArrowDownIcon />
    </div>
    <div :class="[$style.selector_wrapper]" @click="openDropdown($event)">
      <select :value="birthday.month" @change="selectItem($event, 'month')">
        <option disabled selected value="">月</option>
        <option
          v-for="month in monthOptions"
          :key="month.value"
          :value="month.value"
        >
          {{ month.label }}
        </option>
      </select>
      <KeyboardArrowDownIcon />
    </div>
    <div
      v-if="type === 'date'"
      :class="[$style.selector_wrapper]"
      @click="openDropdown($event)"
    >
      <select :value="birthday.day" @change="selectItem($event, 'day')">
        <option disabled selected value="">日</option>
        <option v-for="day in dayOptions" :key="day.value" :value="day.value">
          {{ day.label }}
        </option>
      </select>
      <KeyboardArrowDownIcon />
    </div>
    <TextButton
      text="削除"
      variant="caution"
      :class="$style.delete_button"
      @click="birthday = { year: '', month: '', day: '' }"
    />
  </InputBox>
</template>

<style lang="scss" module>
@use '@/assets/scss/mixin' as *;

.date_selector {
  width: max-content;
  display: flex;
  align-items: center;
  position: relative;

  > * {
    &:not(:last-of-type) {
      &:after {
        content: '/';
      }
    }
  }
}

.selector_wrapper {
  position: relative;
  width: max-content;

  > svg {
    @include icon($color: var(--link-color));
    position: absolute;
    margin: auto;
    top: 0;
    right: var(--sp-small);
    bottom: 0;
    pointer-events: none;
  }

  &:has(select:focus) {
    svg {
      rotate: 180deg;
    }
  }

  > select {
    width: calc(3ch + (var(--sp-medium) * 2) + var(--icon-medium));
    padding: var(--sp-medium);
    padding-inline-end: calc((var(--sp-small) * 2) + var(--icon-medium));
    cursor: pointer;

    &.year {
      width: calc(5ch + (var(--sp-medium) * 2) + var(--icon-medium));
    }
  }
}

.delete_button {
  margin-inline: var(--sp-medium);
  font-size: var(--fs-small);
}
</style>

// packages/react/src/components/DateSelector.tsx
'use client'

import type { CSSProperties, MouseEvent } from 'react'
import { useEffect, useState } from 'react'
import { daysInMonth, splitDate } from '@geckou/ui-core'
import { InputBox } from './InputBox'
import { KeyboardArrowDownIcon } from './icons/KeyboardArrowDownIcon'
import { COLOR } from '../constants'

type Birthday = {
  year: string
  month: string
  day: string
}

type Props = {
  name: string
  value?: string
  onChange?: (newValue: string) => void
  isRequired?: boolean
}

const EMPTY_BIRTHDAY: Birthday = { year: '', month: '', day: '' }

export function DateSelector({ name, value, onChange, isRequired }: Props) {
  const [birthday, setBirthday] = useState<Birthday>(EMPTY_BIRTHDAY)

  // Vue 版（@geckou/ui-vue）は value が空に戻されたときリセットされなかった
  useEffect(() => {
    if (value) {
      setBirthday(splitDate(value))
    } else {
      setBirthday(EMPTY_BIRTHDAY)
    }
  }, [value])

  const today = new Date()
  const maxYear = today.getFullYear() - 100
  const currentYear = today.getFullYear() - 14
  const yearsOptions = Array.from(
    { length: currentYear - maxYear + 1 },
    (_, i) => (maxYear + i).toString()
  ).map((year) => ({ label: year, value: year }))

  const monthOptions = Array.from({ length: 12 }, (_, i) => {
    const month = (i + 1).toString()
    return { label: month, value: month.padStart(2, '0') }
  })

  // 年が未選択のときは閏年を含む最大日数になるよう 2000 年を使う
  const getDaysInMonth = (year: string, month: string) =>
    daysInMonth(Number(year) || 2000, Number(month))

  const selectedMonthDays = getDaysInMonth(birthday.year, birthday.month)
  const dayOptions = Array.from({ length: selectedMonthDays }, (_, i) => {
    const day = (i + 1).toString()
    return { label: day, value: day.padStart(2, '0') }
  })

  const emitBirthday = (next: Birthday) => {
    setBirthday(next)
    if (!next.year && !next.month && !next.day) {
      onChange?.('')
    } else if (!next.year || !next.month || !next.day) {
      return
    } else {
      onChange?.(`${next.year}-${next.month}-${next.day}`)
    }
  }

  const selectItem = (key: keyof Birthday, newValue: string) => {
    const next = { ...birthday, [key]: newValue }

    // 月・年を変えて日が存在しなくなった場合は、その月の末日に丸める
    if (key !== 'day' && next.day && next.month) {
      const maxDay = getDaysInMonth(next.year, next.month)
      if (Number(next.day) > maxDay) {
        next.day = String(maxDay).padStart(2, '0')
      }
    }

    emitBirthday(next)
  }

  const openDropdown = (event: MouseEvent<HTMLDivElement>) => {
    const target = event.currentTarget
    const select = target.firstElementChild as HTMLSelectElement | null
    if (select) {
      select.click()
    }
  }

  const wrapperClass = 'relative w-max [&:has(select:focus)>svg]:rotate-180'
  const iconClass =
    'pointer-events-none absolute inset-y-0 right-[var(--sp-small,0.375rem)] m-auto size-[var(--icon-medium,1.125rem)] fill-(--icon-color)'
  const selectClass =
    'w-[calc(3ch+var(--sp-medium,0.75rem)*2+var(--icon-medium,1.125rem))]! p-[var(--sp-medium,0.75rem)]! pe-[calc(var(--sp-small,0.375rem)*2+var(--icon-medium,1.125rem))]! cursor-pointer'
  const wrapperStyle = { '--icon-color': COLOR.blue } as CSSProperties
  const deleteButtonStyle = { '--caution-color': COLOR.red } as CSSProperties

  return (
    <InputBox className="flex w-max items-center [&>*:not(:last-of-type)]:after:content-['/']">
      <div className={wrapperClass} style={wrapperStyle} onClick={openDropdown}>
        <select
          value={birthday.year}
          name={`${name}-year`}
          required={isRequired}
          onChange={(event) => selectItem('year', event.target.value)}
          className="w-[calc(5ch+var(--sp-medium,0.75rem)*2+var(--icon-medium,1.125rem))]! cursor-pointer p-[var(--sp-medium,0.75rem)]! pe-[calc(var(--sp-small,0.375rem)*2+var(--icon-medium,1.125rem))]!"
        >
          <option disabled value="">
            年
          </option>
          {yearsOptions.map((year) => (
            <option key={year.value} value={year.value}>
              {year.label}
            </option>
          ))}
        </select>
        <KeyboardArrowDownIcon className={iconClass} />
      </div>
      <div className={wrapperClass} style={wrapperStyle} onClick={openDropdown}>
        <select
          value={birthday.month}
          name={`${name}-month`}
          required={isRequired}
          onChange={(event) => selectItem('month', event.target.value)}
          className={selectClass}
        >
          <option disabled value="">
            月
          </option>
          {monthOptions.map((month) => (
            <option key={month.value} value={month.value}>
              {month.label}
            </option>
          ))}
        </select>
        <KeyboardArrowDownIcon className={iconClass} />
      </div>
      <div className={wrapperClass} style={wrapperStyle} onClick={openDropdown}>
        <select
          value={birthday.day}
          name={`${name}-day`}
          required={isRequired}
          onChange={(event) => selectItem('day', event.target.value)}
          className={selectClass}
        >
          <option disabled value="">
            日
          </option>
          {dayOptions.map((day) => (
            <option key={day.value} value={day.value}>
              {day.label}
            </option>
          ))}
        </select>
        <KeyboardArrowDownIcon className={iconClass} />
      </div>
      <button
        type="button"
        style={deleteButtonStyle}
        className="mx-[var(--sp-medium,0.75rem)] inline-flex cursor-pointer items-center gap-[var(--sp-min,0.1875rem)] text-[length:var(--fs-small,0.6875rem)] text-(--caution-color)"
        onClick={() => emitBirthday(EMPTY_BIRTHDAY)}
      >
        削除
      </button>
    </InputBox>
  )
}
