// packages/vue/src/components/DropdownUi.vue
<script setup lang="ts">
import { ref, onBeforeUnmount, onMounted } from 'vue'
import IconChevronDown from '@/components/Icon/KeyboardArrowDownIcon.vue'
import { useClickOutside } from '@/scripts/use-click-outside'
import { nextUniqueId } from '@/scripts/unique-id'
withDefaults(
  defineProps<{
    isHiddenArrow?: boolean
    contentAlignment?: 'left' | 'center' | 'right'
    isDisabled?: boolean
    contentsWidth?: string
  }>(),
  {
    isHiddenArrow: false,
    contentAlignment: 'left',
    isDisabled: false,
    contentsWidth: 'auto',
  }
)

const isContentsOpened = ref(false)
const root = ref<HTMLElement | null>(null)
const contents = ref<HTMLElement | null>(null)
const trigger = ref<HTMLButtonElement | null>(null)
const contentsHeight = ref(0)

// aria-controls でトリガーとパネルを結ぶための id
const panelId = nextUniqueId('dropdown') + '_panel'

const toggleBox = () => (isContentsOpened.value = !isContentsOpened.value)
const closeDropDown = () => (isContentsOpened.value = false)

// Escape で閉じ、トリガーへフォーカスを戻す。戻さないと、閉じた瞬間に
// フォーカスが body へ落ちてキーボード操作の位置を見失う
const closeAndRefocus = (event: KeyboardEvent) => {
  if (!isContentsOpened.value) {
    return
  }

  // 自分が処理した印を残す。ModalBox の中に置いたとき、
  // ダイアログまで一緒に閉じるのを防ぐ
  event.preventDefault()
  closeDropDown()
  trigger.value?.focus()
}

const updateContentsHeight = () => {
  const contentsValue = contents.value
  if (contentsValue) {
    contentsHeight.value = contentsValue.clientHeight
  }
}

useClickOutside(root, () => closeDropDown())

// onUpdated はこのコンポーネントが再描画されたときしか走らない。
// スロットの中の子コンポーネントが自前の状態で伸縮すると高さがずれるため、
// 要素そのものを ResizeObserver で見る
let observer: ResizeObserver | null = null

onMounted(() => {
  updateContentsHeight()

  const contentsValue = contents.value

  if (!contentsValue || typeof ResizeObserver === 'undefined') {
    return
  }

  observer = new ResizeObserver(updateContentsHeight)
  observer.observe(contentsValue)
})

onBeforeUnmount(() => observer?.disconnect())
// React 版（DropdownUiHandle）と揃えて close も公開する
defineExpose({ isContentsOpened, close: closeDropDown })
</script>

<template>
  <div
    ref="root"
    :class="$style.drop_down_box"
    @keydown.escape="closeAndRefocus"
  >
    <button
      ref="trigger"
      :class="$style.button"
      :disabled="isDisabled"
      :aria-expanded="isContentsOpened"
      aria-haspopup="true"
      :aria-controls="$slots.contents ? panelId : undefined"
      type="button"
      :style="{
        '--trigger-color':
          isDisabled || !$slots.contents
            ? 'var(--text-color)'
            : 'var(--link-color)',
        cursor: isDisabled || !$slots.contents ? 'auto' : 'pointer',
      }"
      @click.prevent="toggleBox"
    >
      <slot name="trigger" />
      <IconChevronDown
        v-if="!(isHiddenArrow || !$slots.contents || isDisabled)"
        :class="[$style.icon, { [$style.open]: isContentsOpened }]"
      />
    </button>
    <div
      v-if="$slots.contents"
      :id="panelId"
      :class="$style.contents"
      :inert="!isContentsOpened || undefined"
      :style="{
        boxShadow: isContentsOpened ? 'var(--box-shadow)' : 'none',
        blockSize: isContentsOpened ? `${contentsHeight}px` : 0,
        inlineSize: contentsWidth,
        right: contentAlignment === 'right' ? 'calc(var(--bv) * -0.5)' : 'auto',
        left: contentAlignment === 'left' ? 'calc(var(--bv) * -0.5)' : 'auto',
        zIndex: '2',
      }"
    >
      <div ref="contents" @click="closeDropDown">
        <slot name="contents" />
      </div>
    </div>
  </div>
</template>

<style lang="scss" module>
@use '@/assets/scss/mixin' as *;

.drop_down_box {
  position: relative;
}

.button {
  display: flex;
  align-items: center;
  inline-size: 100%;
  block-size: 100%;
  gap: var(--sp-small);
  color: var(--trigger-color);
}

.icon {
  @include icon($size: var(--icon-small));
  flex: 0 0 auto;
  transition: all 0.1s;

  &.open {
    transform: rotate(180deg);
  }
}

.contents {
  border-radius: var(--radius-small);
  position: absolute;
  top: calc(100% - var(--sp-min));
  transition: block-size 0.1s;
  overflow: hidden;
  cursor: pointer;

  > div {
    max-block-size: calc(var(--bv) * 48);
    min-inline-size: calc(var(--bv) * 20);
    background-color: var(--white);
    overflow: auto;
  }
}
</style>

// packages/react/src/components/DropdownUi.tsx
'use client'

import type { CSSProperties, ReactNode, Ref } from 'react'
import { useEffect, useId, useImperativeHandle, useRef, useState } from 'react'
import { KeyboardArrowDownIcon } from './icons/KeyboardArrowDownIcon'
import { COLOR } from '../constants'

// Vue 版（@geckou/ui-vue）の defineExpose({ isContentsOpened }) 相当
export type DropdownUiHandle = {
  isContentsOpened: () => boolean
  close: () => void
}

type Props = {
  isHiddenArrow?: boolean
  contentAlignment?: 'left' | 'center' | 'right'
  isDisabled?: boolean
  contentsWidth?: string
  trigger: ReactNode
  contents?: ReactNode
  ref?: Ref<DropdownUiHandle>
}

export function DropdownUi({
  isHiddenArrow = false,
  contentAlignment = 'left',
  isDisabled = false,
  contentsWidth = 'auto',
  trigger,
  contents,
  ref,
}: Props) {
  const [isContentsOpened, setIsContentsOpened] = useState(false)
  const [contentsHeight, setContentsHeight] = useState(0)
  const rootRef = useRef<HTMLDivElement>(null)
  const contentsRef = useRef<HTMLDivElement>(null)
  const triggerRef = useRef<HTMLButtonElement>(null)

  // aria-controls でトリガーとパネルを結ぶための id。
  // 1 画面に複数置いても衝突しないよう useId から作る
  const panelId = `${useId()}-panel`

  const toggleBox = () => setIsContentsOpened((current) => !current)
  const closeDropDown = () => setIsContentsOpened(false)

  // Escape で閉じ、トリガーへフォーカスを戻す。戻さないと、閉じた瞬間に
  // フォーカスが body へ落ちてキーボード操作の位置を見失う
  const closeAndRefocus = () => {
    closeDropDown()
    triggerRef.current?.focus()
  }

  useImperativeHandle(ref, () => ({
    isContentsOpened: () => isContentsOpened,
    close: closeDropDown,
  }))

  useEffect(() => {
    const handleClickOutside = (event: PointerEvent) => {
      const root = rootRef.current
      if (root && !root.contains(event.target as Node)) {
        closeDropDown()
      }
    }

    document.addEventListener('pointerdown', handleClickOutside)
    return () => document.removeEventListener('pointerdown', handleClickOutside)
  }, [])

  useEffect(() => {
    const contentsElement = contentsRef.current
    if (!contentsElement) {
      return
    }

    const updateContentsHeight = () =>
      setContentsHeight(contentsElement.clientHeight)

    updateContentsHeight()
    const observer = new ResizeObserver(updateContentsHeight)
    observer.observe(contentsElement)
    return () => observer.disconnect()
    // eslint-disable-next-line react-hooks/exhaustive-deps -- サイズ変化は ResizeObserver が検知するため、contents の有無が変わったときだけ再登録する
  }, [Boolean(contents)])

  const isInactive = isDisabled || !contents

  const style = {
    '--trigger-color': isInactive ? COLOR.black : COLOR.blue,
  } as CSSProperties

  const contentsStyle: CSSProperties = {
    boxShadow: isContentsOpened ? '0 0 6px #33333333' : 'none',
    blockSize: isContentsOpened ? `${contentsHeight}px` : 0,
    inlineSize: contentsWidth,
    right:
      contentAlignment === 'right'
        ? 'calc(var(--bv, 0.375rem) * -0.5)'
        : 'auto',
    left:
      contentAlignment === 'left' ? 'calc(var(--bv, 0.375rem) * -0.5)' : 'auto',
    zIndex: 2,
  }

  return (
    <div
      ref={rootRef}
      className="relative"
      onKeyDown={(event) => {
        if (event.key !== 'Escape' || !isContentsOpened) {
          return
        }

        // 自分が処理した印を残す。ModalBox の中に置いたとき、
        // ダイアログまで一緒に閉じるのを防ぐ
        event.preventDefault()
        closeAndRefocus()
      }}
    >
      <button
        ref={triggerRef}
        type="button"
        disabled={isDisabled}
        aria-expanded={isContentsOpened}
        aria-haspopup="true"
        aria-controls={contents ? panelId : undefined}
        style={{ ...style, cursor: isInactive ? 'auto' : 'pointer' }}
        className="flex size-full items-center gap-[var(--sp-small,0.375rem)] text-(--trigger-color)"
        onClick={(event) => {
          event.preventDefault()
          toggleBox()
        }}
      >
        {trigger}
        {!(isHiddenArrow || !contents || isDisabled) && (
          <KeyboardArrowDownIcon
            className={`size-[var(--icon-small,0.9375rem)] flex-none transition-all duration-100 ${isContentsOpened ? 'rotate-180' : ''}`}
          />
        )}
      </button>
      {contents && (
        <div
          id={panelId}
          style={contentsStyle}
          inert={!isContentsOpened}
          className="absolute top-[calc(100%-var(--sp-min,0.1875rem))] cursor-pointer overflow-hidden rounded-[var(--radius-small,0.1875rem)] transition-[block-size] duration-100"
        >
          <div
            ref={contentsRef}
            className="max-h-[calc(var(--bv,0.375rem)*56)] min-w-[calc(var(--bv,0.375rem)*20)] overflow-auto bg-white"
            onClick={closeDropDown}
          >
            {contents}
          </div>
        </div>
      )}
    </div>
  )
}
