// packages/vue/src/components/SelectBox.vue
<script setup lang="ts">
import type { Option, InputBoxStyleForEachStatus } from '@/types'
import { ref, computed, watch } from 'vue'
import { isEmptyValue, MESSAGES } from '@geckou/ui-core'
import InputBox from '@/components/InputBox.vue'
import ErrorMessage from '@/components/ErrorMessage.vue'
import KeyboardArrowDownIcon from '@/components/Icon/KeyboardArrowDownIcon.vue'

type SelectValue = string | number

const emit = defineEmits<{
  (e: 'update:modelValue', newValue: SelectValue): void
}>()

const props = withDefaults(
  defineProps<{
    options: Array<Option | Record<string, Option[]>>
    name: string
    modelValue?: SelectValue
    cssStyle?: InputBoxStyleForEachStatus | undefined
    placeholder?: string
    canOmitSelect?: boolean
    isDisabled?: boolean
    isRequired?: boolean
  }>(),
  {
    modelValue: undefined,
    cssStyle: undefined,
    placeholder: '選択してください',
  }
)

const errorMessages = ref<Array<string>>([])

const selectedValue = computed<SelectValue>({
  get: () => props.modelValue ?? '',
  set: (newValue: SelectValue) => emit('update:modelValue', newValue),
})

const isOption = (obj: unknown): obj is Option => {
  return (
    typeof obj === 'object' &&
    obj !== null &&
    'label' in obj &&
    typeof obj.label === 'string' &&
    'value' in obj
  )
}

const validateValue = () => {
  errorMessages.value = []
  // 未選択の判定は truthy ではなく「空かどうか」で行う。
  // SelectValue は string | number なので、0 は正当な選択値
  if (isEmptyValue(selectedValue.value) && props.isRequired) {
    errorMessages.value.push(MESSAGES.required)
  }
}

watch(
  () => selectedValue.value,
  () => validateValue(),
  { immediate: !isEmptyValue(props.modelValue), flush: 'post' }
)
</script>

<template>
  <InputBox
    :cssStyle="cssStyle"
    :class="$style.select_box"
    :isDisabled="isDisabled"
    :isErrored="!!errorMessages.length"
  >
    <select
      v-model="selectedValue"
      :name="name"
      :disabled="isDisabled"
      :required="isRequired"
      :aria-invalid="errorMessages.length > 0 || undefined"
      :class="$style.select"
      @blur="validateValue()"
    >
      <option v-if="canOmitSelect" value="">
        {{ placeholder || '選択しない' }}
      </option>
      <option v-else disabled selected value="">
        {{ placeholder || '選択してください' }}
      </option>
      <template
        v-for="option in options"
        :key="isOption(option) ? option.value : Object.keys(option)[0]"
      >
        <option
          v-if="isOption(option)"
          :value="option.value"
          :disabled="option.isDisabled"
        >
          {{ option.label }}
        </option>
        <template v-else>
          <optgroup v-for="(opt, key) in option" :key="key" :label="key">
            <option
              v-for="o in opt"
              :key="o.value"
              :value="o.value"
              :disabled="o.isDisabled"
            >
              {{ o.label }}
            </option>
          </optgroup>
          <hr />
        </template>
      </template>
    </select>
    <div :class="$style.arrow_container">
      <slot name="arrow" />
      <KeyboardArrowDownIcon v-if="!$slots.arrow" :class="$style.arrow" />
    </div>
    <ErrorMessage
      :errorMessages="errorMessages"
      :cssStyle="{
        textColor: cssStyle?.error?.backgroundColor,
        backgroundColor: cssStyle?.error?.textColor,
      }"
    />
  </InputBox>
</template>

<style lang="scss" module>
:is(.select_box) {
  display: inline-flex;

  > select {
    flex: 1 1 auto;
    padding-inline-end: 2rem;
    cursor: pointer;
  }
}

:is(.arrow_container) {
  display: flex;
  align-items: center;
  position: absolute;
  margin: auto;
  inset-inline-end: 0.5rem;
  inset-block: 0;
  pointer-events: none;

  > * {
    color: currentColor;
    fill: currentColor;
    block-size: 1rem;
  }
}
</style>

// packages/react/src/components/SelectBox.tsx
'use client'

import type { ReactNode } from 'react'
import type { Option, InputBoxStyleForEachStatus, SelectValue } from '../types'
import { MESSAGES } from '@geckou/ui-core'
import { Fragment, useEffect, useRef, useState } from 'react'
import { InputBox } from './InputBox'
import { ErrorMessage } from './ErrorMessage'
import { KeyboardArrowDownIcon } from './icons/KeyboardArrowDownIcon'

type Props = {
  options: Array<Option | Record<string, Option[]>>
  name: string
  value?: SelectValue
  onChange?: (newValue: SelectValue) => void
  cssStyle?: InputBoxStyleForEachStatus
  placeholder?: string
  canOmitSelect?: boolean
  isDisabled?: boolean
  isRequired?: boolean
  arrow?: ReactNode
}

function isOption(obj: unknown): obj is Option {
  return (
    typeof obj === 'object' &&
    obj !== null &&
    'label' in obj &&
    typeof obj.label === 'string' &&
    'value' in obj
  )
}

export function SelectBox({
  options,
  name,
  value,
  onChange,
  cssStyle,
  placeholder = '選択してください',
  canOmitSelect,
  isDisabled,
  isRequired,
  arrow,
}: Props) {
  const [errorMessages, setErrorMessages] = useState<string[]>([])
  const selectedValue = value ?? ''

  const validateValue = () => {
    const messages: string[] = []
    // 数値 0 も正当な選択値として扱うため、truthy 判定ではなく空文字と比較する
    if (selectedValue === '' && isRequired) {
      messages.push(MESSAGES.required)
    }
    setErrorMessages(messages)
  }

  // Vue 版（@geckou/ui-vue）の watch(immediate: !!modelValue) と等価:
  // 初期値ありならマウント時にも検証、以後は値が変化したときのみ検証
  const initialValue = useRef(selectedValue)
  const hasChanged = useRef(false)

  useEffect(() => {
    if (!hasChanged.current) {
      if (selectedValue === initialValue.current) {
        if (selectedValue !== '') {
          validateValue()
        }
        return
      }
      hasChanged.current = true
    }

    validateValue()
    // eslint-disable-next-line react-hooks/exhaustive-deps -- Vue 版（@geckou/ui-vue）同様、値の変化時のみ検証する
  }, [selectedValue])

  const flattenedOptions = options.flatMap((option) =>
    isOption(option) ? [option] : Object.values(option).flat()
  )

  const handleChange = (rawValue: string) => {
    const matched = flattenedOptions.find(
      (option) => String(option.value) === rawValue
    )
    onChange?.(matched ? matched.value : rawValue)
  }

  return (
    <InputBox
      cssStyle={cssStyle}
      className="inline-flex [&>select]:flex-auto [&>select]:cursor-pointer [&>select]:pe-8"
      isDisabled={isDisabled}
      isErrored={!!errorMessages.length}
    >
      <select
        name={name}
        value={selectedValue}
        disabled={isDisabled}
        required={isRequired}
        aria-invalid={errorMessages.length > 0 || undefined}
        onChange={(event) => handleChange(event.target.value)}
        onBlur={() => validateValue()}
      >
        {canOmitSelect ? (
          <option value="">{placeholder || '選択しない'}</option>
        ) : (
          <option disabled value="">
            {placeholder || '選択してください'}
          </option>
        )}
        {options.map((option) =>
          isOption(option) ? (
            <option
              key={option.value}
              value={option.value}
              disabled={option.isDisabled}
            >
              {option.label}
            </option>
          ) : (
            <Fragment key={Object.keys(option)[0]}>
              {Object.entries(option).map(([key, groupedOptions]) => (
                <optgroup key={key} label={key}>
                  {groupedOptions.map((groupedOption) => (
                    <option
                      key={groupedOption.value}
                      value={groupedOption.value}
                      disabled={groupedOption.isDisabled}
                    >
                      {groupedOption.label}
                    </option>
                  ))}
                </optgroup>
              ))}
              <hr />
            </Fragment>
          )
        )}
      </select>
      <div className="pointer-events-none absolute inset-y-0 end-2 flex items-center [&>*]:h-4 [&>*]:fill-current [&>*]:text-current">
        {arrow ?? <KeyboardArrowDownIcon />}
      </div>
      <ErrorMessage
        errorMessages={errorMessages}
        cssStyle={{
          textColor: cssStyle?.error?.backgroundColor,
          backgroundColor: cssStyle?.error?.textColor,
        }}
      />
    </InputBox>
  )
}
