// packages/vue/src/components/TextBox.vue
<script lang="ts" setup>
import type { Validates, InputBoxStyleForEachStatus } from '@/types'
import { ref, computed, watch } from 'vue'
import {
  convertFullWidthToHalfWidth,
  isEmptyValue,
  validateInputValue,
} from '@geckou/ui-core'
import InputBox from '@/components/InputBox.vue'
import ErrorMessage from '@/components/ErrorMessage.vue'

type InputValue = string | number

const emit = defineEmits<{
  (e: 'update:modelValue', newValue: InputValue): void
}>()

const props = withDefaults(
  defineProps<{
    name: string
    modelValue?: InputValue
    cssStyle?: InputBoxStyleForEachStatus | undefined
    inputType?: string
    placeholder?: string
    isDisabled?: boolean
    isRequired?: boolean
    maxLength?: number
    autocomplete?: string
    validates?: Validates
  }>(),
  {
    modelValue: undefined,
    cssStyle: undefined,
    inputType: 'text',
    placeholder: '入力してください',
    maxLength: 30,
    autocomplete: 'off',
    validates: () => [],
  }
)

const errorMessages = ref<string[]>([])

const inputValue = computed<InputValue>({
  get: () => props.modelValue ?? '',
  set: (newValue: InputValue) => {
    const convertedValue =
      typeof newValue === 'number'
        ? newValue
        : convertFullWidthToHalfWidth(String(newValue))

    emit('update:modelValue', convertedValue)
  },
})

const validateValue = () => {
  errorMessages.value = validateInputValue(inputValue.value, {
    isRequired: props.isRequired,
    validates: props.validates,
  })
}

// 初期値があるときはマウント時にも検証する。
// 数値 0 も初期値として扱うため truthy 判定は使わない
watch(inputValue, () => validateValue(), {
  immediate: !isEmptyValue(props.modelValue),
  flush: 'post',
})
</script>

<template>
  <InputBox
    :cssStyle="cssStyle"
    :class="$style.text_box"
    :isErrored="!!errorMessages.length"
    :isDisabled="isDisabled"
  >
    <slot name="before" />
    <input
      v-model="inputValue"
      :type="inputType"
      :name="name"
      :required="isRequired"
      :placeholder="placeholder"
      :disabled="isDisabled"
      :autocomplete="autocomplete"
      :maxlength="maxLength"
      :aria-invalid="!!errorMessages.length ? 'true' : undefined"
      @blur="validateValue()"
    />
    <slot name="after" />
    <ErrorMessage
      :errorMessages="errorMessages"
      :cssStyle="{
        textColor: cssStyle?.error?.backgroundColor,
        backgroundColor: cssStyle?.error?.textColor,
      }"
    />
  </InputBox>
</template>

<style lang="scss" module>
:is(.text_box) {
  display: inline-flex;

  > input {
    flex: 1 1 auto;
  }
}
</style>

// packages/react/src/components/TextBox.tsx
'use client'

import type { ReactNode } from 'react'
import type { InputBoxStyleForEachStatus, Validates } from '../types'
import {
  convertFullWidthToHalfWidth,
  isEmptyValue,
  validateInputValue,
} from '@geckou/ui-core'
import { useEffect, useRef, useState } from 'react'
import { InputBox } from './InputBox'
import { ErrorMessage } from './ErrorMessage'

type InputValue = string | number

type Props = {
  name: string
  value?: InputValue
  onChange?: (newValue: InputValue) => void
  cssStyle?: InputBoxStyleForEachStatus
  inputType?: string
  placeholder?: string
  isDisabled?: boolean
  isRequired?: boolean
  maxLength?: number
  autocomplete?: string
  validates?: Validates
  before?: ReactNode
  after?: ReactNode
}

export function TextBox({
  name,
  value,
  onChange,
  cssStyle,
  inputType = 'text',
  placeholder = '入力してください',
  isDisabled,
  isRequired,
  maxLength = 30,
  autocomplete = 'off',
  validates = [],
  before,
  after,
}: Props) {
  const [errorMessages, setErrorMessages] = useState<string[]>([])
  const inputValue = value ?? ''

  const validateValue = () => {
    setErrorMessages(validateInputValue(inputValue, { isRequired, validates }))
  }

  // Vue 版（@geckou/ui-vue）の watch(immediate: !!modelValue) と等価:
  // 初期値ありならマウント時にも検証、以後は値が変化したときのみ検証
  const initialValue = useRef(inputValue)
  const hasChanged = useRef(false)

  useEffect(() => {
    if (!hasChanged.current) {
      if (inputValue === initialValue.current) {
        if (!isEmptyValue(inputValue)) validateValue()
        return
      }
      hasChanged.current = true
    }

    validateValue()
    // eslint-disable-next-line react-hooks/exhaustive-deps -- Vue 版（@geckou/ui-vue）同様、値の変化時のみ検証する
  }, [inputValue])

  const isComposing = useRef(false)

  return (
    <InputBox
      cssStyle={cssStyle}
      className="inline-flex [&>input]:flex-auto"
      isErrored={!!errorMessages.length}
      isDisabled={isDisabled}
    >
      {before}
      <input
        type={inputType}
        name={name}
        value={inputValue}
        required={isRequired}
        placeholder={placeholder}
        disabled={isDisabled}
        autoComplete={autocomplete}
        maxLength={maxLength}
        aria-invalid={errorMessages.length ? 'true' : undefined}
        onChange={(event) => {
          // IME 変換中に全角→半角変換すると未確定文字列が壊れるため、確定後に変換する
          const rawValue = event.target.value
          onChange?.(
            isComposing.current
              ? rawValue
              : convertFullWidthToHalfWidth(rawValue),
          )
        }}
        onCompositionStart={() => {
          isComposing.current = true
        }}
        onCompositionEnd={(event) => {
          isComposing.current = false
          onChange?.(convertFullWidthToHalfWidth(event.currentTarget.value))
        }}
        onBlur={() => validateValue()}
      />
      {after}
      <ErrorMessage
        errorMessages={errorMessages}
        cssStyle={{
          textColor: cssStyle?.error?.backgroundColor,
          backgroundColor: cssStyle?.error?.textColor,
        }}
      />
    </InputBox>
  )
}
