// packages/vue/src/components/ToggleButton.vue
<script setup lang="ts">
import type { BaseStyle, StyleForEachStatus } from '@/types'
import { computed } from 'vue'
import { COLOR } from '@/const'

type ToggleStyle = {
  on: BaseStyle
  off: BaseStyle
}

// 送信用の <input> を <button> の外へ出したため複数ルートになる。
// 属性は自動継承されないので、明示的に button へ渡す
defineOptions({ inheritAttrs: false })

const emit = defineEmits<{
  (e: 'update:modelValue', newValue: boolean): void
}>()

const props = withDefaults(
  defineProps<{
    name: string
    label?: Record<'on' | 'off', string>
    modelValue?: boolean
    isDisabled?: boolean
    // React 版（ToggleButton.tsx）と揃える。default 以外は任意
    cssStyle?: StyleForEachStatus<ToggleStyle>
    /** アクセシブル名。可視ラベルがあるなら ariaLabelledBy でその要素を指すこと */
    ariaLabel?: string
    ariaLabelledBy?: string
  }>(),
  {
    label: () => ({ on: 'ON', off: 'OFF' }),
    cssStyle: undefined,
    ariaLabel: undefined,
    ariaLabelledBy: undefined,
  }
)

const isChecked = computed<boolean>({
  get: () => props.modelValue ?? false,
  set: (newValue: boolean) => emit('update:modelValue', newValue),
})

const maxTextLength = computed<number>(() => {
  const onLength = props.label.on.length
  const offLength = props.label.off.length

  return onLength > offLength ? onLength : offLength
})

const currentCssStyle = computed(() => {
  const cssStyle = props.isDisabled
    ? props.cssStyle?.disabled
    : props.cssStyle?.default

  return {
    on: {
      ...{
        textColor: props.isDisabled ? COLOR.lightGray : COLOR.white,
        backgroundColor: props.isDisabled ? COLOR.gray : COLOR.blue,
        border: {
          color: props.isDisabled ? COLOR.gray : COLOR.blue,
          size: '1px',
          radius: '.25rem',
        },
        boxShadow: '0 0 0 0 rgba(0, 0, 0, 0)',
      },
      ...cssStyle?.on,
    },
    off: {
      ...{
        textColor: props.isDisabled ? COLOR.gray : COLOR.white,
        backgroundColor: props.isDisabled ? COLOR.lightGray : COLOR.darkGray,
        border: {
          color: props.isDisabled ? COLOR.gray : COLOR.darkGray,
          size: '1px',
          radius: '.25rem',
        },
        boxShadow: '0 0 0 0 rgba(0, 0, 0, 0)',
      },
      ...cssStyle?.off,
    },
  }[isChecked.value ? 'on' : 'off']
})
</script>

<template>
  <button
    v-bind="$attrs"
    :class="$style.toggle_button"
    :style="{
      '--text-color': currentCssStyle?.textColor,
      '--border-color': currentCssStyle?.border?.color,
      '--border-size': currentCssStyle?.border?.size,
      '--radius-size': currentCssStyle?.border?.radius,
      '--background-color': currentCssStyle?.backgroundColor,
      '--box-shadow': currentCssStyle?.boxShadow,
      '--inline-size': `${maxTextLength * 2}ch`,
    }"
    type="button"
    :disabled="isDisabled"
    role="switch"
    :data-checked="isChecked"
    :aria-checked="isChecked"
    :aria-labelledby="ariaLabelledBy"
    :aria-label="ariaLabelledBy ? undefined : (ariaLabel ?? name)"
    @click.stop="!isDisabled ? (isChecked = !isChecked) : null"
  >
    <div
      :class="[$style.text, { [$style.on]: isChecked }]"
      :data-on="label.on"
      :data-off="label.off"
    />
    <div :class="$style.handle" />
  </button>
  <!--
    値の送信専用。<button> の content model は interactive content を許さないので
    中に <input> は置けない。ON のときだけ hidden として外に出す
    （OFF なら送られない、というネイティブの挙動はそのまま）
  -->
  <input
    v-if="isChecked"
    type="hidden"
    :name="name"
    value="on"
    :disabled="isDisabled"
  />
</template>

<style lang="scss" module>
:is(.toggle_button) {
  --handle-size: 1.5rem;
  --padding-size: calc(var(--border-size) + 2px);
  --duration: 0.15s;
  inline-size: calc(
    var(--inline-size) + var(--handle-size) + (var(--padding-size) * 2)
  );
  position: relative;
  display: inline-block;
  padding: var(--padding-size);
  background-color: var(--background-color);
  box-shadow:
    0 0 0 var(--border-size) var(--border-color) inset,
    var(--box-shadow);
  border: none;
  border-radius: var(--radius-size);
  cursor: pointer;
}

:is(.text) {
  position: absolute;
  inline-size: 100%;
  block-size: 100%;
  text-transform: uppercase;
  color: var(--text-color);
  top: 0;
  left: 0;

  &::before,
  &::after {
    display: inline-flex;
    justify-content: center;
    align-items: center;
    block-size: 100%;
    inline-size: calc(100% - var(--handle-size) - var(--padding-size));
    margin: auto;
    line-height: 1;
    position: absolute;
    transition: opacity var(--duration) ease-out;
  }

  &::before {
    content: attr(data-off);
    right: 0;
  }

  &::after {
    content: attr(data-on);
    left: 0;
    opacity: 0;
  }

  &.on {
    &:before {
      opacity: 0;
    }
    &:after {
      opacity: 1;
    }

    + .handle {
      left: calc(100% - var(--handle-size));
    }
  }
}

:is(.handle) {
  inline-size: var(--handle-size);
  aspect-ratio: 1 / 1;
  margin: 0;
  background-color: var(--text-color);
  border-radius: calc(var(--radius-size) - (var(--padding-size) / 2));
  box-shadow: var(--box-shadow);
  position: relative;
  left: 0;
  transition: left var(--duration) ease-out;
}
</style>

// packages/react/src/components/ToggleButton.tsx
'use client'

import type { CSSProperties } from 'react'
import type { BaseStyle, StyleForEachStatus } from '../types'
import { COLOR } from '../constants'

type ToggleStyle = {
  on: BaseStyle
  off: BaseStyle
}

type Props = {
  name: string
  label?: Record<'on' | 'off', string>
  checked?: boolean
  onChange?: (newValue: boolean) => void
  isDisabled?: boolean
  cssStyle?: StyleForEachStatus<ToggleStyle>
  /** アクセシブル名。可視ラベルがあるなら ariaLabelledBy でその要素を指すこと */
  ariaLabel?: string
  ariaLabelledBy?: string
}

export function ToggleButton({
  name,
  label = { on: 'ON', off: 'OFF' },
  checked,
  onChange,
  isDisabled,
  cssStyle,
  ariaLabel,
  ariaLabelledBy,
}: Props) {
  const isChecked = checked ?? false
  const maxTextLength = Math.max(label.on.length, label.off.length)
  const baseStyle = isDisabled ? cssStyle?.disabled : cssStyle?.default

  const currentCssStyle = {
    on: {
      textColor: isDisabled ? COLOR.lightGray : COLOR.white,
      backgroundColor: isDisabled ? COLOR.gray : COLOR.blue,
      border: {
        color: isDisabled ? COLOR.gray : COLOR.blue,
        size: '1px',
        radius: '.25rem',
      },
      boxShadow: '0 0 0 0 rgba(0, 0, 0, 0)',
      ...baseStyle?.on,
    },
    off: {
      textColor: isDisabled ? COLOR.gray : COLOR.white,
      backgroundColor: isDisabled ? COLOR.lightGray : COLOR.darkGray,
      border: {
        color: isDisabled ? COLOR.gray : COLOR.darkGray,
        size: '1px',
        radius: '.25rem',
      },
      boxShadow: '0 0 0 0 rgba(0, 0, 0, 0)',
      ...baseStyle?.off,
    },
  }[isChecked ? 'on' : 'off']

  const style = {
    '--text-color': currentCssStyle.textColor,
    '--border-color': currentCssStyle.border?.color,
    '--border-size': currentCssStyle.border?.size,
    '--radius-size': currentCssStyle.border?.radius,
    '--background-color': currentCssStyle.backgroundColor,
    '--box-shadow': currentCssStyle.boxShadow,
    '--inline-size': `${maxTextLength * 2}ch`,
    '--handle-size': '1.5rem',
    '--padding-size': 'calc(var(--border-size) + 2px)',
    '--duration': '.15s',
  } as CSSProperties

  return (
    <>
      <button
        type="button"
        style={style}
        disabled={isDisabled}
        role="switch"
        aria-checked={isChecked}
        data-checked={isChecked}
        aria-labelledby={ariaLabelledBy}
        aria-label={ariaLabelledBy ? undefined : (ariaLabel ?? name)}
        onClick={(event) => {
          event.stopPropagation()
          if (!isDisabled) {
            onChange?.(!isChecked)
          }
        }}
        className="relative inline-block w-[calc(var(--inline-size)+var(--handle-size)+(var(--padding-size)*2))] cursor-pointer rounded-(--radius-size) border-none bg-(--background-color) p-(--padding-size) shadow-[0_0_0_var(--border-size)_var(--border-color)_inset,var(--box-shadow)] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-(--border-color)"
      >
        <div
          data-on={label.on}
          data-off={label.off}
          className={`absolute top-0 left-0 h-full w-full text-(--text-color) uppercase before:absolute before:right-0 before:m-auto before:inline-flex before:h-full before:w-[calc(100%-var(--handle-size)-var(--padding-size))] before:items-center before:justify-center before:leading-none before:transition-opacity before:duration-(--duration) before:ease-out before:content-[attr(data-off)] after:absolute after:left-0 after:m-auto after:inline-flex after:h-full after:w-[calc(100%-var(--handle-size)-var(--padding-size))] after:items-center after:justify-center after:leading-none after:transition-opacity after:duration-(--duration) after:ease-out after:content-[attr(data-on)] ${isChecked ? 'before:opacity-0 after:opacity-100' : 'before:opacity-100 after:opacity-0'}`}
        />
        <div
          className={`relative m-0 aspect-square w-(--handle-size) rounded-[calc(var(--radius-size)-(var(--padding-size)/2))] bg-(--text-color) shadow-(--box-shadow) transition-[left] duration-(--duration) ease-out ${isChecked ? 'left-[calc(100%-var(--handle-size))]' : 'left-0'}`}
        />
      </button>
      {/*
        値の送信専用。<button> の content model は interactive content を許さないので
        中に <input> は置けない。ON のときだけ hidden として外に出す
        （OFF なら送られない、というネイティブの挙動はそのまま）
      */}
      {isChecked && (
        <input type="hidden" name={name} value="on" disabled={isDisabled} />
      )}
    </>
  )
}
