// packages/react/src/components/CheckBoxes.tsx
'use client'

import type { Option, SelectValue, CheckBoxStyleForEachStatus } from '../types'
import { MESSAGES } from '@geckou/ui-core'
import { useEffect, useRef, useState } from 'react'
import { LabeledCheckbox } from './LabeledCheckbox'
import { ErrorMessage } from './ErrorMessage'
import { COLOR } from '../constants'

type Props = {
  name: string
  options: Option[]
  value?: SelectValue[]
  onChange?: (newValue: SelectValue[]) => void
  isDisabled?: boolean
  isRequired?: boolean
  cssStyle?: CheckBoxStyleForEachStatus
}

export function CheckBoxes({
  name,
  options,
  value,
  onChange,
  isDisabled,
  isRequired,
  cssStyle,
}: Props) {
  const [checkedValues, setCheckedValues] = useState<SelectValue[]>(value ?? [])
  const [errorMessage, setErrorMessage] = useState('')

  const validateInput = (newValues: SelectValue[]) =>
    setErrorMessage(
      isRequired && newValues.length === 0 ? MESSAGES.required : ''
    )

  const isFirstRender = useRef(true)

  useEffect(() => {
    if (isFirstRender.current) {
      isFirstRender.current = false
      if (value?.length) {
        validateInput(value)
      }
      return
    }

    if (value) {
      setCheckedValues(value)
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps -- Vue 版（@geckou/ui-vue）同様、外部からの値変更時のみ同期する
  }, [value])

  const toggleValue = (optionValue: SelectValue, checked: boolean) => {
    const newValues = options
      .map((option) => option.value)
      .filter((candidate) =>
        candidate === optionValue ? checked : checkedValues.includes(candidate)
      )

    setCheckedValues(newValues)
    validateInput(newValues)
    onChange?.(newValues)
  }

  const errorColor = {
    ...(cssStyle?.error ?? {}),
    textColor: COLOR.white,
    backgroundColor: COLOR.red,
    border: {
      color: COLOR.red,
      size: '1px',
      radius: '.25rem',
    },
  }

  return (
    <div className="relative flex flex-wrap gap-x-6 gap-y-4">
      {options.map((option) => (
        <LabeledCheckbox
          key={option.value}
          name={name}
          label={option.label}
          checked={checkedValues.includes(option.value)}
          onChange={(checked) => toggleValue(option.value, checked)}
          isDisabled={isDisabled}
          cssStyle={cssStyle}
        />
      ))}
      <ErrorMessage
        errorMessages={errorMessage ? [errorMessage] : []}
        cssStyle={{
          textColor: errorColor.textColor,
          backgroundColor: errorColor.backgroundColor,
        }}
      />
    </div>
  )
}

// packages/vue/src/components/CheckBoxes.vue
<script setup lang="ts">
import type { Option, SelectValue, CheckBoxStyleForEachStatus } from '@/types'
import { computed, ref, watch } from 'vue'
import { MESSAGES } from '@geckou/ui-core'
import LabeledCheckbox from '@/components/LabeledCheckbox.vue'
import ErrorMessage from '@/components/ErrorMessage.vue'
import { COLOR } from '@/const'

const emit = defineEmits<{
  (e: 'update:modelValue', newValue: SelectValue[]): void
}>()

const props = withDefaults(
  defineProps<{
    name: string
    options: Array<Option>
    modelValue?: SelectValue[]
    isDisabled?: boolean
    isRequired?: boolean
    cssStyle?: CheckBoxStyleForEachStatus
  }>(),
  {
    modelValue: undefined,
    cssStyle: undefined,
  }
)

const checkBoxes = ref(
  props.options.map((option) => ({
    value: option.value,
    label: option.label,
    checked: props.modelValue?.includes(option.value) || false,
  }))
)

const checkedValues = computed<SelectValue[]>(() =>
  checkBoxes.value
    .filter((checkBox) => checkBox.checked)
    .map((checkBox) => checkBox.value)
)
const errorMessage = ref('')
const validateInput = () =>
  (errorMessage.value =
    props.isRequired && checkedValues.value.length === 0
      ? MESSAGES.required
      : '')

watch(
  checkedValues,
  (newValue, oldValue) => {
    const isArraysEqual = (a: SelectValue[], b: SelectValue[]): boolean =>
      a.length === b.length && a.every((val, index) => val === b[index])
    if (oldValue && isArraysEqual(newValue, oldValue)) {
      return
    }
    validateInput()
    emit('update:modelValue', newValue)
  },
  {
    deep: true,
    immediate: !!props.modelValue?.length,
  }
)

watch(
  () => props.modelValue,
  (newValue) => {
    if (!newValue) {
      return
    }
    checkBoxes.value.forEach(
      (checkBox) => (checkBox.checked = newValue.includes(checkBox.value))
    )
  },
  {
    deep: true,
    immediate: true,
  }
)

const errorColor = {
  ...(props.cssStyle?.error ?? {}),
  textColor: COLOR.white,
  backgroundColor: COLOR.red,
  border: {
    color: COLOR.red,
    size: '1px',
    radius: '.25rem',
  },
}
</script>

<template>
  <div :class="$style.check_boxes">
    <!-- key / name にラベルを使うとラベル重複で衝突する。
         name はグループ共通にし、区別は value で行う（ネイティブ送信の作法） -->
    <template v-for="(checkBox, index) in checkBoxes" :key="checkBox.value">
      <LabeledCheckbox
        v-model="checkBoxes[index].checked"
        :name="name"
        :value="checkBox.value"
        :label="checkBox.label"
        :isDisabled="props.isDisabled"
        :cssStyle="props.cssStyle"
      />
    </template>
    <ErrorMessage
      :errorMessages="errorMessage ? [errorMessage] : []"
      :cssStyle="{
        textColor: errorColor.textColor,
        backgroundColor: errorColor.backgroundColor,
      }"
    />
  </div>
</template>

<style lang="scss" module>
.check_boxes {
  display: flex;
  flex-wrap: wrap;
  gap: 1rem 1.5rem;
  position: relative;
}
</style>
