// packages/react/src/components/CheckButton.tsx
'use client'

import type { CSSProperties, ReactNode } from 'react'
import type { CheckBoxStyleForEachStatus } from '../types'
import { CheckIcon } from './icons/CheckIcon'

type Props = {
  name: string
  checked?: boolean
  onChange?: (newValue: boolean) => void
  isDisabled?: boolean
  cssStyle?: CheckBoxStyleForEachStatus
  isDisableAnimation?: boolean
  check?: ReactNode
}

export function CheckButton({
  name,
  checked,
  onChange,
  isDisabled,
  cssStyle = { default: {} },
  isDisableAnimation,
  check,
}: Props) {
  const isChecked = checked ?? false
  const currentCssStyle = isDisabled ? cssStyle.disabled : cssStyle.default

  const style = {
    '--border-color': currentCssStyle?.border?.color || 'blue',
    '--border-size': currentCssStyle?.border?.size || '1px',
    '--radius-size': currentCssStyle?.border?.radius || '0.25rem',
    '--background-color': currentCssStyle?.backgroundColor || '#fff',
    '--duration': isDisableAnimation ? '0s' : '.3s',
  } as CSSProperties

  return (
    <>
      <style>
        {
          '@keyframes uiCheckPop{0%{scale:1}10%{scale:.8}50%{scale:1.1}100%{scale:1}}'
        }
      </style>
      <label
        style={style}
        className={`relative flex h-6 w-6 cursor-pointer items-center justify-center rounded-(--radius-size) shadow-[0_0_0_var(--border-size)_var(--border-color)_inset] has-[input:disabled]:pointer-events-none has-[input:disabled]:before:pointer-events-auto has-[input:disabled]:before:absolute has-[input:disabled]:before:inset-0 has-[input:disabled]:before:cursor-not-allowed has-[input:disabled]:before:content-[''] has-[input:focus-visible]:outline-2 has-[input:focus-visible]:outline-offset-2 has-[input:focus-visible]:outline-(--border-color) ${isChecked ? 'animate-[uiCheckPop_var(--duration)_ease-out] bg-(--border-color)' : 'bg-(--background-color)'}`}
      >
        <input
          type="checkbox"
          name={name}
          checked={isChecked}
          disabled={isDisabled}
          onChange={(event) => {
            if (!isDisabled) {
              onChange?.(event.target.checked)
            }
          }}
          className="sr-only"
        />
        <div
          className={`flex h-4 w-4 items-center justify-center [&>*]:fill-current [&>*]:text-current ${isChecked ? 'text-(--background-color)' : 'text-(--border-color)'}`}
        >
          {check ?? <CheckIcon />}
        </div>
      </label>
    </>
  )
}

// packages/vue/src/components/CheckButton.vue
<script setup lang="ts">
import type { CheckBoxStyleForEachStatus } from '@/types'
import { ref, computed, watch } from 'vue'
import CheckIcon from '@/components/Icon/CheckIcon.vue'

const emit = defineEmits<{
  (e: 'update:modelValue', newValue: boolean): void
}>()

const props = withDefaults(
  defineProps<{
    name: string
    modelValue?: boolean
    isDisabled?: boolean
    cssStyle?: CheckBoxStyleForEachStatus
    isDisableAnimation?: boolean
  }>(),
  {
    cssStyle: () => ({ default: {} }),
  }
)

const isChecked = ref(props.modelValue ?? false)

const currentCssStyle = computed(() => {
  if (props.isDisabled) {
    return props.cssStyle.disabled
  } else {
    return props.cssStyle.default
  }
})

watch(
  () => isChecked.value,
  (newValue) => emit('update:modelValue', newValue)
)
watch(
  () => props.modelValue,
  (newValue) => (isChecked.value = newValue),
  { immediate: true }
)
</script>

<template>
  <span
    :class="$style.check_box"
    :style="{
      '--border-color': currentCssStyle?.border?.color || 'blue',
      '--border-size': currentCssStyle?.border?.size || '1px',
      '--radius-size': currentCssStyle?.border?.radius || '0.25rem',
      '--background-color': currentCssStyle?.backgroundColor || '#fff',
      '--duration': isDisableAnimation ? '0s' : '.3s',
    }"
    @click="isChecked = !isChecked"
  >
    <input
      v-model="isChecked"
      type="checkbox"
      :name="name"
      :disabled="isDisabled"
    />
    <div :class="$style.check_container">
      <slot name="check" />
      <CheckIcon v-if="!$slots.check" />
    </div>
  </span>
</template>

<style lang="scss" module>
@keyframes pop {
  0% {
    scale: 1;
  }

  10% {
    scale: 0.8;
  }

  50% {
    scale: 1.1;
  }

  100% {
    scale: 1;
  }
}

:is(.check_box) {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 1.5rem;
  height: 1.5rem;
  box-shadow: 0 0 0 var(--border-size) var(--border-color) inset;
  border-radius: var(--radius-size);
  background-color: var(--background-color);
  cursor: pointer;

  > input {
    display: none;
  }

  &:has(input:disabled) {
    pointer-events: none !important;

    &::before {
      content: '';
      position: absolute;
      inset: 0;
      pointer-events: all;
      cursor: not-allowed !important;
    }
  }

  &:has(input:checked) {
    background-color: var(--border-color);
    animation: pop var(--duration) ease-out;

    :is(.check_container) {
      color: var(--background-color);
    }
  }
}

:is(.check_container) {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 1rem;
  height: 1rem;
  color: var(--border-color);

  > * {
    color: currentColor;
    fill: currentColor;
  }
}
</style>
