// packages/react/src/components/ErrorMessage.tsx
import type { CSSProperties } from 'react'
import { COLOR } from '../constants'

type Props = {
  /** aria-describedby から参照させたいときに渡す */
  id?: string
  errorMessages?: string[]
  cssStyle?: {
    textColor?: string
    backgroundColor?: string
  }
}

export function ErrorMessage({ id, errorMessages, cssStyle }: Props) {
  if (!errorMessages || !errorMessages.length) {
    return null
  }

  const style = {
    '--error-text-color': cssStyle?.textColor || COLOR.white,
    '--error-background-color': cssStyle?.backgroundColor || COLOR.red,
  } as CSSProperties

  return (
    <div
      id={id}
      role="alert"
      className="absolute top-[calc(100%+0.25rem)] flex w-max flex-col gap-2 rounded-sm bg-(--error-background-color) px-3 py-2 text-sm leading-none text-(--error-text-color) shadow-[0_0_0.5rem_0.25rem_#33333322] before:absolute before:bottom-[calc(100%-1px)] before:left-[0.85rem] before:block before:h-[0.53rem] before:w-[0.85rem] before:bg-(--error-background-color) before:content-[''] before:[clip-path:polygon(50%_0%,100%_100%,0%_100%)]"
      style={style}
    >
      {/* 同じ文言の validates を複数渡せるので、キーは位置で振る */}
      {errorMessages.map((message, index) => (
        <span key={index}>{message}</span>
      ))}
    </div>
  )
}

// packages/vue/src/components/ErrorMessage.vue
<script lang="ts" setup>
import { COLOR } from '@/const'
const { red: cautionColor } = COLOR

defineProps<{
  /** aria-describedby から参照させたいときに渡す */
  id?: string
  cssStyle?: {
    textColor: string | undefined
    backgroundColor: string | undefined
  }
  errorMessages?: Array<string>
}>()
</script>

<template>
  <div
    v-show="errorMessages && errorMessages.length"
    :id="id"
    role="alert"
    :class="$style.error_messages"
    :style="{
      '--error-text-color': cssStyle?.textColor || '#fff',
      '--error-background-color': cssStyle?.backgroundColor || cautionColor,
    }"
  >
    <!-- 同じ文言の validates を複数渡せるので、キーは位置で振る -->
    <span v-for="(message, index) in errorMessages" :key="index">
      {{ message }}
    </span>
  </div>
</template>

<style lang="scss" module>
:is(.error_messages) {
  inline-size: max-content;
  display: flex;
  flex-direction: column;
  gap: 0.5rem;
  padding: 0.5rem 0.75rem;
  font-size: small;
  color: var(--error-text-color);
  background-color: var(--error-background-color);
  box-shadow: 0 0 0.5rem 0.25rem #33333322;
  border-radius: 0.25rem;
  line-height: 1;
  position: absolute;
  inset-block-start: calc(100% + 0.25rem);

  &::before {
    --tail-size: 0.85rem;
    content: '';
    display: block;
    background-color: var(--error-background-color);
    inline-size: var(--tail-size);
    block-size: calc(var(--tail-size) * 0.625);
    clip-path: polygon(50% 0%, 100% 100%, 0% 100%);
    position: absolute;
    bottom: calc(100% - 1px);
    inset-inline-start: 0.85rem;
  }
}
</style>
