// packages/react/src/components/LabeledFieldset.tsx
import type { ReactNode } from 'react'

type Props = {
  isDisabled?: boolean
  label?: ReactNode
  children: ReactNode
}

export function LabeledFieldset({ isDisabled, label, children }: Props) {
  return (
    <div className="grid gap-2">
      <fieldset className="contents" disabled={isDisabled}>
        {label && <legend className="flex items-center">{label}</legend>}
        <div className="[&>*]:w-full">{children}</div>
      </fieldset>
    </div>
  )
}

// packages/vue/src/components/LabeledFieldset.vue
<script setup lang="ts">
defineProps<{ isDisabled?: boolean }>()
</script>

<template>
  <div :class="$style.fieldset">
    <fieldset :disabled="isDisabled">
      <legend v-if="$slots.label" :class="$style.legend">
        <slot name="label" />
      </legend>
      <div :class="$style.input">
        <slot />
      </div>
    </fieldset>
  </div>
</template>

<style lang="scss" module>
:is(.fieldset) {
  display: grid;
  gap: 0.5rem;

  > fieldset {
    display: contents;
  }
}

:is(.legend) {
  display: flex;
  align-items: center;
}

:is(.input) {
  > * {
    inline-size: 100%;
  }
}
</style>
