// packages/react/src/components/ModalBox.tsx
'use client'

import type { ReactNode } from 'react'
import { useEffect, useId, useRef } from 'react'
import { createScrollLock, handleTabKey } from '@geckou/ui-core'

type Props = {
  isShown: boolean
  size?: 'small' | 'medium' | 'large'
  onClose: () => void
  header?: ReactNode
  footer?: ReactNode
  children: ReactNode
  // header が無い場合のダイアログのアクセシブル名
  ariaLabel?: string
}

const MAX_WIDTH_CLASSES = {
  small: 'max-w-[var(--mobile-lower-width,430px)]',
  medium: 'max-w-[var(--desktop-lower-width,1025px)]',
  large: 'max-w-[var(--contents-max-width,1440px)]',
}

function CloseIcon() {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 -960 960 960"
      fill="currentColor"
    >
      <path d="m256-200-56-56 224-224-224-224 56-56 224 224 224-224 56 56-224 224 224 224-56 56-224-224-224 224Z" />
    </svg>
  )
}

export function ModalBox({
  isShown,
  size = 'medium',
  onClose,
  header,
  footer,
  children,
  ariaLabel,
}: Props) {
  const headerId = useId()
  const dialogRef = useRef<HTMLDivElement>(null)

  // body.style.overflow を直接触ると、モーダルを重ねて内側を閉じたときに
  // 外側が開いたままスクロールが戻り、アプリ側のインライン overflow も消える。
  // ロック数を数える実装は @geckou/ui-core に置いて Vue 版と共有している
  const scrollLock = useRef(createScrollLock())

  useEffect(() => {
    const lock = scrollLock.current

    lock.toggle(isShown)

    return () => lock.release()
  }, [isShown])

  // 開く前にフォーカスしていた要素。閉じたらここへ戻す
  // （戻さないとフォーカスが body に落ち、キーボード操作の位置を見失う）
  const lastFocused = useRef<HTMLElement | null>(null)

  useEffect(() => {
    if (isShown) {
      // StrictMode（開発時）は effect を 2 回走らせる。素直に毎回取り直すと、
      // 2 回目は 1 回目の dialogRef.focus() 後なので lastFocused がダイアログ自身になり、
      // 閉じたとき inert なダイアログへ focus() して復帰しない。未設定のときだけ取る
      lastFocused.current ??= document.activeElement as HTMLElement | null
      dialogRef.current?.focus()

      return
    }

    lastFocused.current?.focus()
    lastFocused.current = null
  }, [isShown])

  // Escape で閉じ、Tab / Shift+Tab はダイアログ内で循環させる
  // （role="dialog" は自前で実装する必要がある。背景は inert にしていないので、
  //  トラップが無いと Tab で外のリンクやボタンへ抜ける）
  useEffect(() => {
    if (!isShown) {
      return
    }

    const handleKeyDown = (event: KeyboardEvent) => {
      // 子（SearchableSelectBox の候補リスト等）が Escape を処理した印。
      // 尊重しないと、候補を閉じる操作でダイアログまで閉じてしまう
      if (event.defaultPrevented) {
        return
      }

      if (event.key === 'Escape') {
        onClose()

        return
      }

      handleTabKey(dialogRef.current, event, document.activeElement)
    }

    document.addEventListener('keydown', handleKeyDown)

    return () => document.removeEventListener('keydown', handleKeyDown)
  }, [isShown, onClose])

  return (
    <div
      className={`fixed top-0 left-0 z-50 flex h-dvh w-dvw cursor-pointer items-center justify-center overflow-hidden bg-[#33333380] p-[var(--sp-larger,3rem)] backdrop-blur-sm transition-opacity duration-100 max-md:px-[var(--sp-large,1.5rem)] ${
        isShown
          ? 'pointer-events-auto opacity-100'
          : 'pointer-events-none opacity-0'
      }`}
      aria-hidden={!isShown}
      inert={!isShown}
      onClick={(event) => {
        if (event.target === event.currentTarget) {
          onClose()
        }
      }}
    >
      <div
        ref={dialogRef}
        role="dialog"
        aria-modal="true"
        aria-labelledby={header ? headerId : undefined}
        aria-label={header ? undefined : (ariaLabel ?? 'ダイアログ')}
        tabIndex={-1}
        className={`relative flex max-h-full w-full cursor-auto flex-col rounded-[var(--radius-small,0.1875rem)] bg-white drop-shadow-[0_0_6px_#33333355] ${MAX_WIDTH_CLASSES[size]}`}
      >
        {header && (
          <header
            id={headerId}
            className="border-b border-[#eee] px-[var(--sp-large,1.5rem)] py-[var(--sp-medium,0.75rem)] max-md:p-[var(--sp-medium,0.75rem)] [&>h2]:font-bold [&>h2]:text-[var(--fs-large,0.875rem)]"
          >
            {header}
          </header>
        )}
        <div className="flex-auto overflow-auto p-[var(--sp-large,1.5rem)] max-md:p-[var(--sp-medium,0.75rem)]">
          {children}
        </div>
        {footer && (
          <footer className="flex justify-center gap-[var(--sp-large,1.5rem)] border-t border-[#eee] px-[var(--sp-large,1.5rem)] py-[var(--sp-medium,0.75rem)] max-md:gap-[var(--sp-medium,0.75rem)] max-md:p-[var(--sp-medium,0.75rem)] max-md:[&>*]:flex-auto">
            {footer}
          </footer>
        )}
        <button
          type="button"
          aria-label="閉じる"
          className="absolute bottom-full left-full size-[var(--icon-medium,1.125rem)] cursor-pointer leading-none text-white focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-white [&>*]:size-full"
          onClick={onClose}
        >
          <CloseIcon />
        </button>
      </div>
    </div>
  )
}

// packages/vue/src/components/ModalBox.vue
<script setup lang="ts">
import { computed, nextTick, onMounted, onBeforeUnmount, ref, watch } from 'vue'
import { createScrollLock, handleTabKey } from '@geckou/ui-core'
import IconClose from '@/components/Icon/CloseIcon.vue'
import { nextUniqueId } from '@/scripts/unique-id'

const props = defineProps<{
  isShown: boolean
  size?: 'small' | 'medium' | 'large'
  /** header スロットを使わない場合のダイアログ名 */
  ariaLabel?: string
}>()

// React 版（ModalBox.tsx）と揃える。header があればそれを名前にする
const headerId = nextUniqueId('modal_header')
const dialog = ref<HTMLElement | null>(null)

// React 版（ModalBox.tsx の onClose）と揃える
const emit = defineEmits<{ (e: 'close'): void }>()

// ロック数を数える実装は @geckou/ui-core に置いて React 版と共有している
// （document の参照は呼び出し時なので SSR でも安全）
const scrollLock = createScrollLock()
const toggleScrollLock = (shouldLock: boolean) => scrollLock.toggle(shouldLock)

// 自発的に閉じたときだけ emit する。親が isShown=false にしたときや unmount 時に
// emit すると、親のハンドラが再入する
const requestClose = () => emit('close')

// スクロールロックは isShown の変化に追従させる（emit とは切り離す）
watch(
  () => props.isShown,
  (newVal) => toggleScrollLock(newVal)
)

// 開いたらダイアログへフォーカスを移し、閉じたら開く前の要素へ戻す
// （戻さないとフォーカスが body に落ち、キーボード操作の位置を見失う）
let lastFocused: HTMLElement | null = null

watch(
  () => props.isShown,
  async (newVal) => {
    if (!newVal) {
      lastFocused?.focus()
      lastFocused = null
      return
    }

    lastFocused =
      typeof document === 'undefined'
        ? null
        : (document.activeElement as HTMLElement | null)
    await nextTick()
    dialog.value?.focus()
  }
)

// inert は HTML の boolean 属性で、値に関係なく「存在すれば有効」。
// Vue は false を inert="false" として出すため、そのまま渡すと
// 表示中も中身を操作できない。属性ごと消すには undefined を渡す
const isInert = computed(() => !props.isShown || undefined)

// Escape で閉じ、Tab / Shift+Tab はダイアログ内で循環させる
// （role="dialog" は自前で実装する必要がある。背景は inert にしていないので、
//  トラップが無いと Tab で外のリンクやボタンへ抜ける）
const handleKeyDown = (event: KeyboardEvent) => {
  if (!props.isShown) {
    return
  }

  // 子（SearchableSelectBox の候補リスト等）がキー入力を処理した印。
  // 尊重しないと、候補を閉じる Escape でダイアログまで閉じてしまう
  // （Tab も同様にスキップする。現状 Tab を握る子はいない）
  if (event.defaultPrevented) {
    return
  }

  if (event.key === 'Escape') {
    requestClose()

    return
  }

  handleTabKey(dialog.value, event, document.activeElement)
}

onMounted(() => {
  toggleScrollLock(props.isShown)
  document.addEventListener('keydown', handleKeyDown)
})

onBeforeUnmount(() => {
  scrollLock.release()
  document.removeEventListener('keydown', handleKeyDown)
})
</script>

<template>
  <div
    :class="[$style.overlay, { [$style.display]: isShown }]"
    :aria-hidden="!isShown"
    :inert="isInert"
    @click.self="requestClose"
  >
    <div
      ref="dialog"
      role="dialog"
      aria-modal="true"
      :aria-labelledby="$slots.header ? headerId : undefined"
      :aria-label="$slots.header ? undefined : (ariaLabel ?? 'ダイアログ')"
      :tabindex="-1"
      :class="[$style.container, $style[size ?? 'medium']]"
    >
      <header v-if="$slots.header" :id="headerId" :class="$style.header">
        <slot name="header" />
      </header>
      <div :class="$style.contents">
        <slot />
      </div>
      <footer v-if="$slots.footer" :class="$style.footer">
        <slot name="footer" />
      </footer>
      <button
        type="button"
        aria-label="閉じる"
        :class="$style.close_button"
        @click="requestClose"
      >
        <IconClose />
      </button>
    </div>
  </div>
</template>

<style lang="scss" module>
@use '@/assets/scss/mixin' as *;

.container {
  display: flex;
  flex-direction: column;
  inline-size: 100%;
  max-inline-size: var(--desktop-lower-width);
  max-block-size: 100%;
  background-color: var(--white);
  border-radius: var(--radius-small);
  cursor: auto;
  filter: drop-shadow(0 0 6px var(--shadow-color, rgba(21, 20, 58, 0.12)));
  position: relative;

  &.small {
    max-inline-size: var(--mobile-lower-width);
  }

  &.large {
    max-inline-size: var(--contents-max-width, 1440px);
  }
}

.header {
  padding: var(--sp-medium) var(--sp-large);
  border-block-end: 1px solid var(--light-border-color);

  > h2 {
    font-size: var(--fs-large);
    font-weight: bold;
  }

  @include media('mobile') {
    padding: var(--sp-medium);
  }
}

.contents {
  flex: 1 1 auto;
  overflow: auto;
  padding: var(--sp-large);

  @include media('mobile') {
    padding: var(--sp-medium);
  }
}

.footer {
  display: flex;
  justify-content: center;
  gap: var(--sp-large);
  padding: var(--sp-medium) var(--sp-large);
  border-block-start: 1px solid var(--light-border-color);

  @include media('mobile') {
    gap: var(--sp-medium);
    padding: var(--sp-medium);

    > * {
      flex: 1 1 auto;
    }
  }
}

.close_button {
  inline-size: var(--icon-medium);
  block-size: var(--icon-medium);
  color: var(--white);
  line-height: 1;
  cursor: pointer;
  position: absolute;
  bottom: 100%;
  left: 100%;

  > * {
    @include icon();
  }
}

.overlay {
  display: flex;
  justify-content: center;
  align-items: center;
  inline-size: 100dvw;
  block-size: 100dvh;
  padding: var(--sp-larger);
  background: var(--overlay-color, rgba(0, 8, 26, 0.5));
  background-blend-mode: multiply;
  backdrop-filter: blur(4px);
  opacity: 0;
  transition: opacity 0.1s linear;
  pointer-events: none;
  position: fixed;
  z-index: var(--z-index-overlay, 90);
  top: 0;
  left: 0;
  cursor: pointer;
  overflow: hidden;

  @include media('mobile') {
    padding-inline: var(--sp-large);
  }

  &.display {
    opacity: 1;
    pointer-events: auto;
    z-index: calc(var(--z-index-nav, 70) + 1);
  }
}
</style>
