// packages/react/src/components/PopupBox.tsx
'use client'

import type { ReactNode, Ref } from 'react'
import { useEffect, useImperativeHandle, useRef, useState } from 'react'
import { createPortal } from 'react-dom'
import { COLOR } from '../constants'

export type PopupBoxHandle = {
  showPopup: () => void
}

type Props = {
  position?: {
    x: 'left' | 'right' | 'center'
    y: 'top' | 'bottom' | 'center'
  }
  ref?: Ref<PopupBoxHandle>
  children: ReactNode
}

const X_CLASSES = {
  left: 'left-[max(calc((100vw-64rem)/2),1rem)]',
  right: 'right-[max(calc((100vw-64rem)/2),1rem)]',
  center: 'inset-0 m-auto',
}

const Y_CLASSES = {
  top: 'top-14',
  bottom: 'bottom-4',
  center: 'inset-0 m-auto',
}

export function PopupBox({
  position = { x: 'right', y: 'top' },
  ref,
  children,
}: Props) {
  const [isShown, setIsShown] = useState(false)
  const [isMounted, setIsMounted] = useState(false)
  const timerRef = useRef<ReturnType<typeof setTimeout> | null>(null)

  useEffect(() => {
    setIsMounted(true)

    return () => {
      if (timerRef.current) {
        clearTimeout(timerRef.current)
      }
    }
  }, [])

  useImperativeHandle(ref, () => ({
    showPopup: () => {
      setIsShown(true)

      if (timerRef.current) {
        clearTimeout(timerRef.current)
      }
      timerRef.current = setTimeout(() => setIsShown(false), 3000)
    },
  }))

  if (!isMounted) {
    return null
  }

  return createPortal(
    <div
      // 3 秒で消える通知。ライブリージョンにしないと支援技術に何も伝わらない
      // （要素は常時 DOM にあり内容だけ差し替わるので、role だけで読み上げ対象になる）
      role="status"
      style={{ borderColor: COLOR.blue }}
      className={`pointer-events-none fixed z-50 h-max w-max max-w-40 rounded-[var(--radius-small,0.1875rem)] border bg-white p-[var(--sp-medium,0.75rem)] transition-[transform,opacity] duration-300 ${X_CLASSES[position.x]} ${Y_CLASSES[position.y]} ${isShown ? 'opacity-100' : 'opacity-0'}`}
    >
      {children}
    </div>,
    document.body
  )
}

// packages/vue/src/components/PopupBox.vue
<script setup lang="ts">
import type { Ref } from 'vue'
import { onBeforeUnmount, ref } from 'vue'
withDefaults(
  defineProps<{
    position?: {
      x: 'left' | 'right' | 'center'
      y: 'top' | 'bottom' | 'center'
    }
  }>(),
  {
    position: () => ({ x: 'right', y: 'top' }),
  }
)

const isShown: Ref<boolean> = ref(false)
let hideTimer: ReturnType<typeof setTimeout> | null = null

const showPopup = () => {
  isShown.value = true

  // 連打されたら前のタイマーを捨てて数え直す（消えるまでの時間を毎回 3 秒にする）
  if (hideTimer !== null) {
    clearTimeout(hideTimer)
  }

  hideTimer = setTimeout(() => {
    isShown.value = false
    hideTimer = null
  }, 3000)
}

// unmount 後に ref を触らないよう解除する
onBeforeUnmount(() => {
  if (hideTimer !== null) {
    clearTimeout(hideTimer)
  }
})

defineExpose({
  showPopup,
})
</script>

<template>
  <teleport to="body">
    <!--
      3 秒で消える通知。ライブリージョンにしないと支援技術に何も伝わらない
      （要素は常時 DOM にあり内容だけ差し替わるので、role だけで読み上げ対象になる）
    -->
    <div
      role="status"
      :class="[
        $style.popup,
        $style[`x-${position.x}`],
        $style[`y-${position.y}`],
        { [$style.show]: isShown },
      ]"
    >
      <slot />
    </div>
  </teleport>
</template>

<style lang="scss" module>
.x {
  &-left {
    left: max(
      calc((100vw - var(--contents-max-width, 1440px)) / 2),
      var(--sp-medium)
    );
  }

  &-right {
    right: max(
      calc((100vw - var(--contents-max-width, 1440px)) / 2),
      var(--sp-medium)
    );
  }

  &-center {
    inset: 0;
    margin: auto;
  }
}

.y {
  &-top {
    top: calc(var(--global-header-height, 0px) - var(--sp-small));
  }

  &-bottom {
    bottom: var(--sp-medium);
  }

  &-center {
    inset: 0;
    margin: auto;
  }
}

.popup {
  position: fixed;
  background-color: var(--white);
  border: 1px solid var(--primary-color);
  padding: var(--sp-medium);
  border-radius: var(--radius-small);
  inline-size: max-content;
  max-inline-size: calc(var(--mobile-lower-width, 430px) / 2);
  block-size: max-content;
  opacity: 0;
  transition: transform, opacity;
  transition-duration: var(--animation-duration, 0.3s);
  pointer-events: none;
  z-index: var(--z-index-overlay, 90);

  &.show {
    opacity: 1;
  }
}
</style>
