// packages/react/src/components/RadioButtons.tsx
'use client'

import type { CSSProperties } from 'react'
import type {
  Option,
  RadioButtonStyleForEachStatus,
  SelectValue,
} from '../types'
import { useEffect, useId, useRef, useState } from 'react'
import { isEmptyValue, MESSAGES } from '@geckou/ui-core'
import { ErrorMessage } from './ErrorMessage'
import { COLOR } from '../constants'

type Props = {
  value: SelectValue
  onChange?: (newValue: SelectValue) => void
  options: Option[]
  name?: string
  isDisabled?: boolean
  isRequired?: boolean
  cssStyle?: RadioButtonStyleForEachStatus
  isDisableAnimation?: boolean
  /**
   * ラジオグループ自体のアクセシブル名。
   * 可視ラベル（見出し等）があるなら ariaLabelledBy でその要素を指すこと
   */
  ariaLabel?: string
  ariaLabelledBy?: string
}

export function RadioButtons({
  value,
  onChange,
  options,
  name,
  isDisabled,
  isRequired,
  cssStyle,
  isDisableAnimation,
  ariaLabel,
  ariaLabelledBy,
}: Props) {
  const selectedValue = value ?? ''

  // Vue 版（RadioButtons.vue）は watch(selectedValue) で判定するので、
  // 初回描画では出さず「値が変化したとき」に空なら出す。
  // isTouched（クリック済み）で見ると、制御コンポーネントの React では
  // クリック直後に値が入るため実質出ないままになる
  const [hasChanged, setHasChanged] = useState(false)
  const previousValue = useRef(selectedValue)

  useEffect(() => {
    if (previousValue.current === selectedValue) return

    previousValue.current = selectedValue
    setHasChanged(true)
  }, [selectedValue])

  const errorMessages =
    hasChanged && isRequired && isEmptyValue(selectedValue)
      ? [MESSAGES.required]
      : undefined
  // Vue 版（@geckou/ui-vue）は option ごとに別の name を振っていたため、
  // ラジオグループとして機能しなかった（フォーム送信・キーボード操作）
  const generatedName = useId()
  const groupName = name ?? generatedName
  // グループ名とエラーを結び付ける。fieldset / legend も role="radiogroup" も
  // 無かったため、支援技術には「何のラジオか」が伝わっていなかった
  const errorId = useId()
  const baseStyle = isDisabled ? cssStyle?.disabled : cssStyle?.default

  const currentCssStyle = {
    textColor: isDisabled ? COLOR.darkGray : COLOR.black,
    backgroundColor: isDisabled ? COLOR.lightGray : COLOR.white,
    border: {
      color: isDisabled ? COLOR.darkGray : COLOR.blue,
      size: '1px',
    },
    ...(baseStyle ?? {}),
  }

  const style = {
    '--text-color': currentCssStyle.textColor,
    '--border-color': currentCssStyle.border?.color,
    '--border-size': currentCssStyle.border?.size,
    '--background-color': currentCssStyle.backgroundColor,
    '--duration': isDisableAnimation ? '0s' : '.3s',
  } as CSSProperties

  return (
    <div
      role="radiogroup"
      aria-label={ariaLabelledBy ? undefined : ariaLabel}
      aria-labelledby={ariaLabelledBy}
      aria-required={isRequired || undefined}
      aria-describedby={errorMessages ? errorId : undefined}
      className="relative flex flex-wrap items-center gap-4"
    >
      <style>
        {
          '@keyframes uiRadioPop{0%{scale:1}10%{scale:.8}50%{scale:1.2}100%{scale:1}}'
        }
      </style>
      {options.map((option) => {
        const isChecked = option.value === selectedValue

        return (
          <label
            key={option.value}
            style={style}
            className={`relative grid cursor-pointer grid-cols-[auto_1fr] items-center gap-2 before:inline-block before:aspect-square before:w-4 before:rounded-full before:transition-all before:duration-(--duration) before:ease-linear before:content-[''] has-[input:disabled]:cursor-not-allowed has-[input:focus-visible]:outline-2 has-[input:focus-visible]:outline-offset-2 has-[input:focus-visible]:outline-(--border-color) ${
              isChecked
                ? 'text-(--text-color) before:animate-[uiRadioPop_var(--duration)_ease-out] before:bg-(--border-color) before:shadow-[0_0_0_2px_var(--background-color)_inset,0_0_0_1px_var(--border-color)]'
                : 'text-(--border-color) before:bg-(--background-color) before:shadow-[0_0_0_1px_var(--border-color)_inset]'
            }`}
          >
            <input
              type="radio"
              name={groupName}
              value={option.value}
              disabled={isDisabled}
              required={isRequired}
              checked={isChecked}
              onChange={() => onChange?.(option.value)}
              className="sr-only"
            />
            <span>{option.label}</span>
          </label>
        )
      })}
      <ErrorMessage id={errorId} errorMessages={errorMessages} />
    </div>
  )
}

// packages/vue/src/components/RadioButtons.vue
<script setup lang="ts">
import type { Option, RadioButtonStyleForEachStatus } from '@/types'
import { ref, watch, computed } from 'vue'
import { isEmptyValue, MESSAGES } from '@geckou/ui-core'
import { COLOR } from '@/const'
import { nextUniqueId } from '@/scripts/unique-id'
import ErrorMessage from '@/components/ErrorMessage.vue'

type SelectValue = string | number

const emit = defineEmits<{
  (e: 'update:modelValue', newValue: SelectValue): void
}>()

const props = withDefaults(
  defineProps<{
    modelValue: SelectValue
    options: Array<Option>
    name?: string
    isDisabled?: boolean
    isRequired?: boolean
    cssStyle?: RadioButtonStyleForEachStatus
    isDisableAnimation?: boolean
    /**
     * ラジオグループ自体のアクセシブル名。
     * 可視ラベル（見出し等）があるなら ariaLabelledBy でその要素を指すこと
     */
    ariaLabel?: string
    ariaLabelledBy?: string
  }>(),
  {
    name: undefined,
    cssStyle: undefined,
    ariaLabel: undefined,
    ariaLabelledBy: undefined,
  }
)

// name を省略したときの一意な既定値
const groupName = props.name ?? nextUniqueId('radio_group')

// グループ名とエラーを結び付ける。fieldset / legend も role="radiogroup" も
// 無かったため、支援技術には「何のラジオか」が伝わっていなかった
const errorId = nextUniqueId('radio_group_error')

const errorMessages = ref<Array<string>>([])

const selectedValue = computed({
  get: () => props.modelValue ?? '',
  set: (newValue: SelectValue) => emit('update:modelValue', newValue),
})

const currentCssStyle = computed(() => {
  const cssStyle = props.isDisabled
    ? props.cssStyle?.disabled
    : props.cssStyle?.default

  return {
    ...{
      textColor: props.isDisabled ? COLOR.darkGray : COLOR.black,
      backgroundColor: props.isDisabled ? COLOR.lightGray : COLOR.white,
      border: {
        color: props.isDisabled ? COLOR.darkGray : COLOR.blue,
        size: '1px',
      },
    },
    ...(cssStyle ?? {}),
  }
})

const validateValue = () => {
  errorMessages.value = []
  // 未選択の判定は truthy ではなく「空かどうか」で行う。
  // SelectValue は string | number なので、0 は正当な選択値
  if (isEmptyValue(selectedValue.value) && props.isRequired) {
    errorMessages.value.push(MESSAGES.required)
  }
}

watch(
  () => selectedValue.value,
  () => validateValue(),
  { immediate: !isEmptyValue(props.modelValue) }
)
</script>

<template>
  <div
    :class="$style.radios"
    role="radiogroup"
    :aria-label="ariaLabelledBy ? undefined : ariaLabel"
    :aria-labelledby="ariaLabelledBy"
    :aria-required="isRequired || undefined"
    :aria-describedby="errorMessages.length ? errorId : undefined"
  >
    <label
      v-for="option in options"
      :key="option.value"
      :class="$style.radio"
      :style="{
        '--text-color': currentCssStyle?.textColor,
        '--border-color': currentCssStyle?.border?.color,
        '--border-size': currentCssStyle?.border?.size,
        '--background-color': currentCssStyle?.backgroundColor,
        '--duration': isDisableAnimation ? '0s' : '.3s',
      }"
    >
      <input
        v-model="selectedValue"
        type="radio"
        :name="groupName"
        :value="option.value"
        :disabled="isDisabled"
        :required="isRequired"
        :checked="option.value === selectedValue"
      />
      <span>
        {{ option.label }}
      </span>
    </label>
    <ErrorMessage :id="errorId" :errorMessages="errorMessages" />
  </div>
</template>

<style lang="scss" module>
@use '@/assets/scss/mixin' as *;

@keyframes pop {
  0% {
    scale: 1;
  }

  10% {
    scale: 0.8;
  }

  50% {
    scale: 1.2;
  }

  100% {
    scale: 1;
  }
}

:is(.radios) {
  display: flex;
  align-items: center;
  flex-wrap: wrap;
  gap: 1rem;
  // ErrorMessage は position: absolute で下に出るので、基準を作る
  position: relative;
}

:is(.radio) {
  display: grid;
  grid-template-columns: auto 1fr;
  align-items: center;
  gap: 0.5rem;
  color: var(--border-color);
  cursor: pointer;

  &::before {
    content: '';
    display: inline-block;
    aspect-ratio: 1 / 1;
    width: 1rem;
    box-shadow: 0 0 0 1px var(--border-color) inset;
    background-color: var(--background-color);
    border-radius: 50%;
    transition: all var(--duration) linear;
  }

  &:has(input:checked) {
    color: var(--text-color);

    &::before {
      box-shadow:
        0 0 0 2px var(--background-color) inset,
        0 0 0 1px var(--border-color);
      background-color: var(--border-color);
      animation: pop var(--duration) ease-out;
    }
  }

  &:has(input:disabled) {
    cursor: not-allowed !important;
  }

  > input {
    @include visually-hidden;
  }
}
</style>
