// packages/react/src/components/SlideDownUi.tsx
'use client'

import type { CSSProperties, ReactNode, Ref } from 'react'
import { useEffect, useImperativeHandle, useRef, useState } from 'react'
import { KeyboardArrowDownIcon } from './icons/KeyboardArrowDownIcon'
import { COLOR } from '../constants'

// Vue 版（@geckou/ui-vue）の defineExpose({ isOpenedContents }) 相当
export type SlideDownUiHandle = {
  isOpenedContents: () => boolean
  close: () => void
}

type Props = {
  isOpened?: boolean | null
  isHiddenArrow?: boolean
  isDisabled?: boolean
  isDisableClickOutside?: boolean
  duration?: number
  trigger: ReactNode
  children: ReactNode
  ref?: Ref<SlideDownUiHandle>
}

export function SlideDownUi({
  isOpened = null,
  isHiddenArrow = false,
  isDisabled = false,
  isDisableClickOutside = false,
  duration = 0.3,
  trigger,
  children,
  ref,
}: Props) {
  const [isOpenedContents, setIsOpenedContents] = useState(isOpened || false)
  const [isOverflowVisible, setIsOverflowVisible] = useState(isOpened || false)
  const [contentsHeight, setContentsHeight] = useState(0)
  const rootRef = useRef<HTMLDivElement>(null)
  const contentsRef = useRef<HTMLDivElement>(null)

  const toggleBox = () => setIsOpenedContents((current) => !current)

  useImperativeHandle(ref, () => ({
    isOpenedContents: () => isOpenedContents,
    close: () => setIsOpenedContents(false),
  }))

  useEffect(() => {
    if (typeof isOpened === 'boolean') {
      setIsOpenedContents(isOpened)
    }
  }, [isOpened])

  useEffect(() => {
    if (isDisableClickOutside) {
      return
    }

    const handleClickOutside = (event: PointerEvent) => {
      const root = rootRef.current
      if (root && !root.contains(event.target as Node)) {
        setIsOpenedContents(false)
      }
    }

    document.addEventListener('pointerdown', handleClickOutside)
    return () => document.removeEventListener('pointerdown', handleClickOutside)
  }, [isDisableClickOutside])

  // 参照するのは ref と setState だけなので依存配列は空でよい。
  // サイズ変化は ResizeObserver が検知する
  useEffect(() => {
    const contentsElement = contentsRef.current
    if (!contentsElement) {
      return
    }

    const updateContentsHeight = () =>
      setContentsHeight(contentsElement.clientHeight)

    updateContentsHeight()
    const observer = new ResizeObserver(updateContentsHeight)
    observer.observe(contentsElement)
    return () => observer.disconnect()
  }, [])

  useEffect(() => {
    if (!isOpenedContents) {
      setIsOverflowVisible(false)
      return
    }

    const timer = setTimeout(() => setIsOverflowVisible(true), duration * 1000)
    return () => clearTimeout(timer)
  }, [isOpenedContents, duration])

  const style = { '--link-color': COLOR.blue } as CSSProperties

  return (
    <div ref={rootRef} style={style}>
      <button
        type="button"
        disabled={isDisabled}
        aria-expanded={isOpenedContents}
        className="relative grid w-full cursor-pointer grid-cols-[1fr_auto] items-center justify-items-start text-(--link-color)"
        onClick={(event) => {
          event.preventDefault()
          toggleBox()
        }}
      >
        <div className="w-full text-left">{trigger}</div>
        {!isHiddenArrow && (
          <KeyboardArrowDownIcon
            className={`size-[var(--icon-medium,1.125rem)] flex-none text-(--link-color) transition-all duration-100 ${isOpenedContents ? 'rotate-180' : ''}`}
          />
        )}
      </button>
      <div
        style={{
          height: isOpenedContents ? `${contentsHeight}px` : 0,
          transitionDuration: `${duration}s`,
          overflow: isOverflowVisible ? 'visible' : 'hidden',
        }}
        inert={!isOpenedContents}
        className="transition-[height]"
      >
        <div ref={contentsRef}>{children}</div>
      </div>
    </div>
  )
}

// packages/vue/src/components/SlideDownUi.vue
<script setup lang="ts">
import type { Ref } from 'vue'
import { ref, onMounted, onUpdated, watch } from 'vue'
import IconChevronDown from '@/components/Icon/KeyboardArrowDownIcon.vue'
import { useClickOutside } from '@/scripts/use-click-outside'
const props = withDefaults(
  defineProps<{
    isOpened?: boolean | null
    isHiddenArrow?: boolean
    isDisabled?: boolean
    isDisableClickOutside?: boolean
    duration?: number
  }>(),
  {
    isOpened: null,
    duration: 0.3,
  }
)

const isOpenedContents = ref(props.isOpened || false)
const root: Ref<HTMLElement | null> = ref(null)
const contents: Ref<HTMLElement | null> = ref(null)
const contentsHeight = ref(0)
const toggleBox = () => (isOpenedContents.value = !isOpenedContents.value)

const close = () => (isOpenedContents.value = false)

const closeDropDown = () => {
  if (!props.isDisableClickOutside) {
    close()
  }
}

const updateContentsHeight = () => {
  const contentsValue = contents.value
  if (contentsValue) {
    contentsHeight.value = contentsValue.clientHeight
  }
}

useClickOutside(root, () => closeDropDown())

onMounted(() => updateContentsHeight())
onUpdated(() => updateContentsHeight())
watch(
  () => props.isOpened,
  (newValue) => {
    if (typeof newValue === 'boolean') {
      isOpenedContents.value = newValue
    }
  }
)
// React 版（SlideDownUiHandle）と揃えて close も公開する。
// 外から閉じる用途なので isDisableClickOutside は見ない
defineExpose({ isOpenedContents, close })
</script>

<template>
  <div
    ref="root"
    :class="{ [$style.opened]: isOpenedContents }"
    :style="{ '--accordion-toggle-duration': `${props.duration}s` }"
  >
    <button
      :class="$style.trigger"
      :disabled="isDisabled"
      :aria-expanded="isOpenedContents"
      type="button"
      @click.prevent="toggleBox"
    >
      <div :class="$style.trigger_content">
        <slot name="trigger" />
      </div>
      <IconChevronDown v-if="!isHiddenArrow" :class="$style.icon" />
    </button>
    <div
      :style="{ height: isOpenedContents ? `${contentsHeight}px` : 0 }"
      :class="$style.contents"
      :inert="!isOpenedContents || undefined"
    >
      <div ref="contents" :class="$style.container">
        <slot />
      </div>
    </div>
  </div>
</template>

<style lang="scss" module>
@use '@/assets/scss/mixin' as *;

@keyframes overflow {
  0% {
    overflow: hidden;
  }

  99% {
    overflow: hidden;
  }

  100% {
    overflow: visible;
  }
}

.trigger_content {
  inline-size: 100%;
  text-align: start;
}

.trigger {
  display: grid;
  grid-template-columns: 1fr auto;
  align-items: center;
  inline-size: 100%;
  justify-items: start;
  cursor: pointer;
  position: relative;
  color: var(--link-color);
}

.icon {
  @include icon($color: var(--link-color));
  flex: 0 0 auto;
  transition: all 0.1s;
}

.contents {
  transition: height var(--accordion-toggle-duration);
  overflow: hidden;
}

.opened {
  .icon {
    transform: rotate(180deg);
  }

  .contents {
    animation: overflow var(--accordion-toggle-duration);
    animation-fill-mode: forwards;
  }
}
</style>
