// packages/react/src/components/TabUI.tsx
'use client'

import type { CSSProperties, KeyboardEvent, ReactNode } from 'react'
import { useId, useRef, useState } from 'react'
import { COLOR } from '../constants'

type Tab = {
  key: string
  label: string
}

type Props = {
  tabs: Tab[]
  color?: {
    active: string
    background: string
    text: string
  }
  initialIndex?: number
  tabSlots?: Record<string, ReactNode>
  panelSlots?: Record<string, ReactNode>
}

export function TabUI({
  tabs,
  color,
  initialIndex = 0,
  tabSlots,
  panelSlots,
}: Props) {
  const [activeTab, setActiveTab] = useState(
    () => tabs[initialIndex]?.key ?? tabs[0]?.key ?? ''
  )
  const tabRefs = useRef<Array<HTMLButtonElement | null>>([])
  // 複数インスタンス設置時の DOM id 重複を避ける
  const uid = useId()
  const tabId = (key: string) => `${uid}-tab-${key}`
  const panelId = (key: string) => `${uid}-panel-${key}`

  const changeTabs = (key: string) => setActiveTab(key)

  const activateTab = (index: number) => {
    setActiveTab(tabs[index].key)
    tabRefs.current[index]?.focus()
  }

  // Vue 版（@geckou/ui-vue）は window 全体に keydown を張っていたため、フォーカス位置と
  // 無関係にタブが切り替わり複数設置時に競合した。タブリストにフォーカスが
  // あるときだけ矢印キーで移動する（WAI-ARIA Tabs パターン）
  const handleKeydown = (event: KeyboardEvent<HTMLDivElement>) => {
    if (event.key !== 'ArrowLeft' && event.key !== 'ArrowRight') {
      return
    }

    const currentIndex = tabs.findIndex((tab) => tab.key === activeTab)
    if (currentIndex === -1) {
      return
    }

    event.preventDefault()
    const lastIndex = tabs.length - 1

    if (event.key === 'ArrowLeft') {
      activateTab(currentIndex > 0 ? currentIndex - 1 : lastIndex)
    } else {
      activateTab(currentIndex < lastIndex ? currentIndex + 1 : 0)
    }
  }

  const style = {
    '--active-color': color?.active || COLOR.blue,
    '--background-color': color?.background || 'transparent',
    '--text-color': color?.text || 'inherit',
  } as CSSProperties

  return (
    <div>
      <div
        style={style}
        className="flex bg-(--background-color)"
        role="tablist"
        onKeyDown={handleKeydown}
      >
        {tabs.map((tab, index) => (
          <button
            key={tab.key}
            id={tabId(tab.key)}
            ref={(el) => {
              tabRefs.current[index] = el
            }}
            type="button"
            role="tab"
            aria-controls={panelId(tab.key)}
            aria-selected={activeTab === tab.key}
            tabIndex={activeTab === tab.key ? 0 : -1}
            className={`border-none bg-transparent px-4 py-2 text-base ${activeTab === tab.key ? 'cursor-auto text-(--active-color)' : 'cursor-pointer text-(--text-color)'}`}
            onClick={() => changeTabs(tab.key)}
          >
            {tabSlots?.[tab.key] ?? tab.label}
          </button>
        ))}
      </div>
      {tabs.map((tab) => (
        <div
          key={`${tab.key}_panel`}
          id={panelId(tab.key)}
          role="tabpanel"
          aria-labelledby={tabId(tab.key)}
          hidden={activeTab !== tab.key}
        >
          {panelSlots?.[`${tab.key}Contents`]}
        </div>
      ))}
    </div>
  )
}

// packages/vue/src/components/TabUI.vue
<script setup lang="ts">
import { ref } from 'vue'
import { COLOR } from '@/const'
import { nextUniqueId } from '@/scripts/unique-id'

const props = withDefaults(
  defineProps<{
    tabs: {
      key: string
      label: string
    }[]
    color?: {
      active: string
      background: string
      text: string
    }
    initialIndex?: number
  }>(),
  {
    color: undefined,
    initialIndex: 0,
  }
)

// 1 画面に複数置いても DOM id が衝突しないよう、インスタンスごとの接頭辞を付ける
const uid = nextUniqueId('tabs')
const tabId = (key: string) => `${uid}_tab_${key}`
const panelId = (key: string) => `${uid}_panel_${key}`

// initialIndex が範囲外でも落とさない（React 版と揃える）
const initialTab = props.tabs[props.initialIndex] ?? props.tabs[0]
const activeTab = ref(initialTab?.key ?? '')
const tabRefs = ref<HTMLButtonElement[]>([])
const changeTabs = (key: string) => (activeTab.value = key)

const activateTab = (index: number) => {
  activeTab.value = props.tabs[index].key
  tabRefs.value[index]?.focus()
}

// 以前は window 全体に keydown を張っていたため、フォーカス位置と無関係にタブが
// 切り替わり、1 画面に複数設置すると互いに競合した。
// タブリストにフォーカスがあるときだけ矢印キーで移動する（WAI-ARIA Tabs パターン）
const handleKeydown = (event: KeyboardEvent) => {
  if (event.key !== 'ArrowLeft' && event.key !== 'ArrowRight') {
    return
  }

  const currentIndex = props.tabs.findIndex(
    (tab) => tab.key === activeTab.value
  )
  if (currentIndex === -1) {
    return
  }

  event.preventDefault()
  const lastIndex = props.tabs.length - 1

  if (event.key === 'ArrowLeft') {
    activateTab(currentIndex > 0 ? currentIndex - 1 : lastIndex)
  } else {
    activateTab(currentIndex < lastIndex ? currentIndex + 1 : 0)
  }
}
</script>

<template>
  <div>
    <div
      :class="$style.tabs"
      :style="{
        '--active-color': color?.active || COLOR.blue,
        '--background-color': color?.background || 'transparent',
        '--text-color': color?.text || 'inherit',
      }"
      role="tablist"
      @keydown="handleKeydown"
    >
      <button
        v-for="(tab, index) in tabs"
        :id="tabId(tab.key)"
        :key="tab.key"
        :ref="
          (el) => {
            if (el) tabRefs[index] = el as HTMLButtonElement
          }
        "
        type="button"
        role="tab"
        :aria-controls="panelId(tab.key)"
        :aria-selected="activeTab === tab.key"
        :tabindex="activeTab === tab.key ? 0 : -1"
        :class="{ [$style.active]: activeTab === tab.key }"
        @click="changeTabs(tab.key)"
      >
        <slot :name="tab.key" />
        <template v-if="!$slots[tab.key]">
          {{ tab.label }}
        </template>
      </button>
    </div>
    <div
      v-for="tab in tabs"
      v-show="activeTab === tab.key"
      :id="panelId(tab.key)"
      :key="`${tab.key}_panel`"
      role="tabpanel"
      :aria-labelledby="tabId(tab.key)"
    >
      <slot :name="`${tab.key}Contents`" />
    </div>
  </div>
</template>

<style lang="scss" module>
.tabs {
  display: flex;
  background-color: var(--background-color);

  > button {
    &[role='tab'] {
      border: none;
      background-color: transparent;
      color: var(--text-color);
      font-size: 1rem;
      padding: 0.5rem 1rem;
      cursor: pointer;

      &.active {
        color: var(--active-color);
        cursor: auto;
      }
    }
  }
}
</style>
