// packages/react/src/components/TextArea.tsx
'use client'

import type { InputBoxStyleForEachStatus, Validates } from '../types'
import { isEmptyValue, validateInputValue } from '@geckou/ui-core'
import { useEffect, useRef, useState } from 'react'
import { InputBox } from './InputBox'
import { ErrorMessage } from './ErrorMessage'

type InputValue = string | null

type Props = {
  name: string
  value?: InputValue
  onChange?: (newValue: InputValue) => void
  cssStyle?: InputBoxStyleForEachStatus
  placeholder?: string
  isDisabled?: boolean
  isRequired?: boolean
  rows?: number
  /** 入力可能な文字数の上限。既定は無制限（`maxlength` 属性を付けない） */
  maxLength?: number
  autocomplete?: string
  validates?: Validates
  autoAdjustHeight?: boolean
}

/**
 * autoAdjustHeight のための高さ。
 *
 * scrollHeight は padding を含み border を含まない。box-sizing によって
 * height が指す範囲が違うので、固定値（以前は padding 決め打ちの 2rem）ではなく
 * 実際の計算値から補正する。border-box のリセット CSS を当てた環境で
 * 2rem 足りず、末尾がスクロールになっていた
 */
function contentHeight(textarea: HTMLTextAreaElement): number {
  const style = getComputedStyle(textarea)
  const sum = (...values: string[]) =>
    values.reduce((total, value) => total + (parseFloat(value) || 0), 0)

  return style.boxSizing === 'border-box'
    ? textarea.scrollHeight + sum(style.borderTopWidth, style.borderBottomWidth)
    : textarea.scrollHeight - sum(style.paddingTop, style.paddingBottom)
}

export function TextArea({
  name,
  value,
  onChange,
  cssStyle,
  placeholder = '入力してください',
  isDisabled,
  isRequired,
  rows,
  maxLength,
  autocomplete = 'off',
  validates = [],
  autoAdjustHeight,
}: Props) {
  const [errorMessages, setErrorMessages] = useState<string[]>([])
  const textareaRef = useRef<HTMLTextAreaElement>(null)
  const inputValue = value ?? ''

  const validateValue = () => {
    setErrorMessages(validateInputValue(inputValue, { isRequired, validates }))
  }

  // Vue 版（@geckou/ui-vue）の watch(immediate: !!modelValue) と等価:
  // 初期値ありならマウント時にも検証、以後は値が変化したときのみ検証
  const initialValue = useRef(inputValue)
  const hasChanged = useRef(false)

  useEffect(() => {
    if (autoAdjustHeight && textareaRef.current) {
      const textarea = textareaRef.current
      textarea.style.height = 'auto'
      textarea.style.height = `${contentHeight(textarea)}px`
    }

    if (!hasChanged.current) {
      if (inputValue === initialValue.current) {
        // 数値 0 も初期値として扱うため truthy 判定は使わない
        if (!isEmptyValue(inputValue)) {
          validateValue()
        }
        return
      }
      hasChanged.current = true
    }

    validateValue()
    // eslint-disable-next-line react-hooks/exhaustive-deps -- Vue 版（@geckou/ui-vue）同様、値の変化時のみ検証・高さ調整する
  }, [inputValue])

  return (
    <InputBox
      cssStyle={cssStyle}
      className="min-h-[4em]"
      isErrored={!!errorMessages.length}
      isDisabled={isDisabled}
    >
      <textarea
        ref={textareaRef}
        name={name}
        value={inputValue}
        required={isRequired}
        placeholder={placeholder}
        disabled={isDisabled}
        autoComplete={autocomplete}
        rows={rows}
        maxLength={maxLength}
        aria-invalid={errorMessages.length ? 'true' : undefined}
        onChange={(event) => onChange?.(event.target.value)}
        onBlur={() => validateValue()}
      />
      <ErrorMessage
        errorMessages={errorMessages}
        cssStyle={{
          textColor: cssStyle?.error?.backgroundColor,
          backgroundColor: cssStyle?.error?.textColor,
        }}
      />
    </InputBox>
  )
}

// packages/vue/src/components/TextArea.vue
<script lang="ts" setup>
import type { Validates, InputBoxStyleForEachStatus } from '@/types'
import { ref, computed, watch, nextTick, onMounted } from 'vue'
import { isEmptyValue, validateInputValue } from '@geckou/ui-core'
import InputBox from '@/components/InputBox.vue'
import ErrorMessage from '@/components/ErrorMessage.vue'

type InputValue = string | null

const emit = defineEmits<{
  (e: 'update:modelValue', newValue: InputValue): void
}>()

const props = withDefaults(
  defineProps<{
    name: string
    modelValue?: InputValue
    cssStyle?: InputBoxStyleForEachStatus | undefined
    placeholder?: string
    isDisabled?: boolean
    isRequired?: boolean
    rows?: number
    /** 入力可能な文字数の上限。既定は無制限（maxlength 属性を付けない） */
    maxLength?: number
    autocomplete?: string
    validates?: Validates
    autoAdjustHeight?: boolean
  }>(),
  {
    modelValue: undefined,
    cssStyle: undefined,
    isRequired: false,
    placeholder: '入力してください',
    rows: undefined,
    maxLength: undefined,
    isDisabled: false,
    autocomplete: 'off',
    validates: () => [],
  }
)

const inputValue = computed<InputValue>({
  get: () => props.modelValue ?? '',
  set: (newValue: InputValue) => emit('update:modelValue', newValue),
})

const errorMessages = ref<string[]>([])
const textareaRef = ref<HTMLTextAreaElement | null>(null)

const validateValue = () => {
  errorMessages.value = validateInputValue(inputValue.value, {
    isRequired: props.isRequired,
    validates: props.validates,
  })
}

/**
 * autoAdjustHeight のための高さ。
 *
 * scrollHeight は padding を含み border を含まない。box-sizing によって
 * height が指す範囲が違うので、固定値（以前は padding 決め打ちの 2rem）ではなく
 * 実際の計算値から補正する。border-box のリセット CSS を当てた環境で
 * 2rem 足りず、末尾がスクロールになっていた
 */
const contentHeight = (textarea: HTMLTextAreaElement): number => {
  const style = getComputedStyle(textarea)
  const sum = (...values: string[]) =>
    values.reduce((total, value) => total + (parseFloat(value) || 0), 0)

  return style.boxSizing === 'border-box'
    ? textarea.scrollHeight + sum(style.borderTopWidth, style.borderBottomWidth)
    : textarea.scrollHeight - sum(style.paddingTop, style.paddingBottom)
}

const adjustTextareaHeight = () => {
  if (!props.autoAdjustHeight) {
    return
  }

  nextTick(() => {
    if (textareaRef.value) {
      textareaRef.value.style.height = 'auto'
      textareaRef.value.style.height = `${contentHeight(textareaRef.value)}px`
    }
  })
}

onMounted(adjustTextareaHeight)

watch(
  inputValue,
  () => {
    validateValue()
    adjustTextareaHeight()
  },
  // 数値 0 も初期値として扱うため truthy 判定は使わない
  { immediate: !isEmptyValue(props.modelValue), flush: 'post' }
)
</script>

<template>
  <InputBox
    :cssStyle="cssStyle"
    :class="$style.text_area"
    :isErrored="!!errorMessages.length"
    :isDisabled="isDisabled"
  >
    <textarea
      ref="textareaRef"
      v-model="inputValue"
      :name="name"
      :required="isRequired"
      :placeholder="placeholder"
      :disabled="isDisabled"
      :autocomplete="autocomplete"
      :rows="rows"
      :maxlength="maxLength"
      :aria-invalid="!!errorMessages.length ? 'true' : undefined"
      @blur="validateValue()"
    />
    <ErrorMessage
      :errorMessages="errorMessages"
      :cssStyle="{
        textColor: cssStyle?.error?.backgroundColor,
        backgroundColor: cssStyle?.error?.textColor,
      }"
    />
  </InputBox>
</template>

<style module>
:is(.text_area) {
  min-block-size: 4em;
}
</style>
